#### imports

In [42]:
import matplotlib.pyplot as plt

In [43]:
import pandas as pd, numpy as np
import seaborn as sns

from sklearn.preprocessing import StandardScaler, OneHotEncoder, TargetEncoder, LabelEncoder

#### load data

In [69]:
data = pd.read_csv(r'C:\Users\psxea2\Desktop\Amdari files\reder-prediction\DataCleaning\cleaned_data1.csv')

In [70]:
data.head()

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,NPS,...,AvgOpenDelay_days,AvgClickDelay_days,OpenRate,ClickRate,ClickToOpenRate,EverOpened,EverClicked,RecencyLastOpen_days,RecencyLastClick_days,customer_segments
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,3,...,818.0,1137.0,1.0,1.0,1.0,1,1,352,33,at_risk
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,6,...,110.0,198.0,1.0,1.0,1.0,1,1,405,317,premium
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,3,...,333.0,450.0,1.0,1.0,1.0,1,1,155,38,need_attention
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,1,...,159.0,582.0,1.0,1.0,1.0,1,1,536,113,loyal
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,3,...,193.0,289.0,1.0,1.0,1.0,1,1,101,5,loyal

In [46]:
data.columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'Location', 'Email', 'Phone',
       'Address', 'Segment', 'NPS', 'ChurnLabel', 'Timestamp', 'Plan',
       'Start_Date', 'End_Date', 'PageViews', 'TimeSpent(minutes)', 'Logins',
       'Frequency', 'Rating', 'Comment', 'TotalPurchaseFrequency',
       'TotalPurchaseValue', 'ProductList', 'PaymentTypes', 'NumPaymentMethod',
       'AvgLatePayment', 'TotalInteractionType', 'num_calls', 'num_emails',
       'num_chats', 'FirstInteractionDate', 'LastInteractionDate',
       'InteractionDuration_days', 'FirstInteractionType',
       'LastInteractionType', 'Action_count', 'FirstActionTime',
       'LastActionTime', 'AvgTimeBetweenActions_secs', 'TotalDaysActive',
       'MostCommonAction', 'LeastFrequentAction', 'ActivityDuration_days',
       'ActionsPerDay', 'most_recent_action_date', 'TotalPageVisits',
       'unique_pages', 'FirstActionType', 'LastActionType', 'FirstPageVisited',
       'LastPageVisited', 'Recency_days', 'InactivityFlag',
       'ActionsLast30Days', 'ActiveInLastWeek', 'TotalEmailsSent',
       'TotalEmailsOpened', 'TotalEmailsClicked', 'LastEmailSentDate',
       'LastEmailOpenedDate', 'LastEmailClickedDate', 'AVGOpenDays',
       'AVGClickDays', 'AvgOpenDelay_days', 'AvgClickDelay_days', 'OpenRate',
       'ClickRate', 'ClickToOpenRate', 'EverOpened', 'EverClicked',
       'RecencyLastOpen_days', 'RecencyLastClick_days', 'customer_segments'],
      dtype='object')

In [74]:
data[['ActivityDuration_days',
       'ActionsPerDay', 'most_recent_action_date', 'TotalPageVisits',
       'unique_pages', 'FirstActionType', 'LastActionType', 'FirstPageVisited',
       'LastPageVisited', 'Recency_days', 'InactivityFlag',
       'ActionsLast30Days', 'ActiveInLastWeek', 'TotalEmailsSent',
       'TotalEmailsOpened', 'TotalEmailsClicked', 'LastEmailSentDate',
       'LastEmailOpenedDate', 'LastEmailClickedDate', 'AVGOpenDays',
       'AVGClickDays', 'AvgOpenDelay_days', 'AvgClickDelay_days', 'OpenRate',
       'ClickRate', 'ClickToOpenRate', 'EverOpened', 'EverClicked',
       'RecencyLastOpen_days', 'RecencyLastClick_days', 'customer_segments']].head()

,ActivityDuration_days,ActionsPerDay,most_recent_action_date,TotalPageVisits,unique_pages,FirstActionType,LastActionType,FirstPageVisited,LastPageVisited,Recency_days,...,AvgOpenDelay_days,AvgClickDelay_days,OpenRate,ClickRate,ClickToOpenRate,EverOpened,EverClicked,RecencyLastOpen_days,RecencyLastClick_days,customer_segments
0,1394,1.043478,2022-11-07 02:24:31,24,13,Search,Search,main,author,53,...,818.0,1137.0,1.0,1.0,1.0,1,1,352,33,at_risk
1,1328,1.000000,2022-12-05 00:27:08,24,13,Click,Add to Cart,homepage,faq,25,...,110.0,198.0,1.0,1.0,1.0,1,1,405,317,premium
2,1335,1.000000,2022-11-02 15:59:43,12,7,Click,Search,author,about,58,...,333.0,450.0,1.0,1.0,1.0,1,1,155,38,need_attention
3,1400,1.021739,2022-12-08 18:10:18,47,14,Add to Cart,Search,category,about,22,...,159.0,582.0,1.0,1.0,1.0,1,1,536,113,loyal
4,1453,1.000000,2022-12-30 23:37:00,30,12,Add to Cart,Search,register,post,0,...,193.0,289.0,1.0,1.0,1.0,1,1,101,5,loyal

In [72]:
data['PaymentTypes']

0        Bank Transfer,Credit Card,PayPal
1        Bank Transfer,Credit Card,PayPal
2        Bank Transfer,Credit Card,PayPal
3        Bank Transfer,Credit Card,PayPal
4        Bank Transfer,Credit Card,PayPal
                       ...
12478    Bank Transfer,Credit Card,PayPal
12479    Bank Transfer,Credit Card,PayPal
12480    Bank Transfer,Credit Card,PayPal
12481    Bank Transfer,Credit Card,PayPal
12482    Bank Transfer,Credit Card,PayPal
Name: PaymentTypes, Length: 12483, dtype: object

#### check and convert  dataypes

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12483 entries, 0 to 12482
Data columns (total 74 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CustomerID                  12483 non-null  int64
 1   Name                        12483 non-null  object
 2   Age                         12483 non-null  int64
 3   Gender                      12483 non-null  object
 4   Location                    12483 non-null  object
 5   Email                       12483 non-null  object
 6   Phone                       12483 non-null  object
 7   Address                     12483 non-null  object
 8   Segment                     12483 non-null  object
 9   NPS                         12483 non-null  int64
 10  ChurnLabel                  12483 non-null  int64
 11  Timestamp                   12483 non-null  object
 12  Plan                        12483 non-null  object
 13  Start_Date                  12483 non-null  object
 14  End_Date                    12483 non-null  object
 15  PageViews                   12483 non-null  int64
 16  TimeSpent(minutes)          12483 non-null  int64
 17  Logins                      12483 non-null  int64
 18  Frequency                   12483 non-null  object
 19  Rating                      12483 non-null  int64
 20  Comment                     12483 non-null  object
 21  TotalPurchaseFrequency      12483 non-null  int64
 22  TotalPurchaseValue          12483 non-null  float64
 23  ProductList                 12483 non-null  object
 24  PaymentTypes                12483 non-null  object
 25  NumPaymentMethod            12483 non-null  int64
 26  AvgLatePayment              12483 non-null  float64
 27  TotalInteractionType        12483 non-null  object
 28  num_calls                   12483 non-null  int64
 29  num_emails                  12483 non-null  int64
 30  num_chats                   12483 non-null  int64
 31  FirstInteractionDate        12483 non-null  object
 32  LastInteractionDate         12483 non-null  object
 33  InteractionDuration_days    12483 non-null  int64
 34  FirstInteractionType        12483 non-null  object
 35  LastInteractionType         12483 non-null  object
 36  Action_count                12483 non-null  int64
 37  FirstActionTime             12483 non-null  object
 38  LastActionTime              12483 non-null  object
 39  AvgTimeBetweenActions_secs  12483 non-null  float64
 40  TotalDaysActive             12483 non-null  int64
 41  MostCommonAction            12483 non-null  object
 42  LeastFrequentAction         12483 non-null  object
 43  ActivityDuration_days       12483 non-null  int64
 44  ActionsPerDay               12483 non-null  float64
 45  most_recent_action_date     12483 non-null  object
 46  TotalPageVisits             12483 non-null  int64
 47  unique_pages                12483 non-null  int64
 48  FirstActionType             12483 non-null  object
 49  LastActionType              12483 non-null  object
 50  FirstPageVisited            12483 non-null  object
 51  LastPageVisited             12483 non-null  object
 52  Recency_days                12483 non-null  int64
 53  InactivityFlag              12483 non-null  int64
 54  ActionsLast30Days           12483 non-null  float64
 55  ActiveInLastWeek            12483 non-null  int64
 56  TotalEmailsSent             12483 non-null  int64
 57  TotalEmailsOpened           12483 non-null  int64
 58  TotalEmailsClicked          12483 non-null  int64
 59  LastEmailSentDate           12483 non-null  object
 60  LastEmailOpenedDate         12483 non-null  object
 61  LastEmailClickedDate        12483 non-null  object
 62  AVGOpenDays                 12483 non-null  float64
 63  AVGClickDays                12483 non-null  float64
 64  AvgOpenDelay_days           12483 non-null  float64
 65  AvgClickDelay_days          12483 non-null  float64
 66  OpenRate                    12483 non-null  float64
 67  ClickRate                   12483 non-null  float64
 68  ClickToOpenRate             12483 non-null  float64
 69  EverOpened                  12483 non-null  int64
 70  EverClicked                 12483 non-null  int64
 71  RecencyLastOpen_days        12483 non-null  int64
 72  RecencyLastClick_days       12483 non-null  int64
 73  customer_segments           12255 non-null  object
dtypes: float64(12), int64(29), object(33)
memory usage: 7.0+ MB

In [49]:
#data.select_dtypes(include= 'datetime').dtypes

date_cols = data[['Start_Date', 'End_Date', 'Timestamp', 'FirstInteractionDate', 
                  'most_recent_action_date', 'LastInteractionDate',
                  'FirstActionTime','LastActionTime', 'LastEmailSentDate','LastEmailOpenedDate', 
                  'LastEmailClickedDate' ]].columns.to_list()

for col in date_cols:
    data[col] = pd.to_datetime(data[col], errors='coerce')




data.select_dtypes(include= 'datetime').dtypes

Timestamp                  datetime64[ns]
Start_Date                 datetime64[ns]
End_Date                   datetime64[ns]
FirstInteractionDate       datetime64[ns]
LastInteractionDate        datetime64[ns]
FirstActionTime            datetime64[ns]
LastActionTime             datetime64[ns]
most_recent_action_date    datetime64[ns]
LastEmailSentDate          datetime64[ns]
LastEmailOpenedDate        datetime64[ns]
LastEmailClickedDate       datetime64[ns]
dtype: object

In [50]:
data.select_dtypes(include=['object']).dtypes

Name                    object
Gender                  object
Location                object
Email                   object
Phone                   object
Address                 object
Segment                 object
Plan                    object
Frequency               object
Comment                 object
ProductList             object
PaymentTypes            object
TotalInteractionType    object
FirstInteractionType    object
LastInteractionType     object
MostCommonAction        object
LeastFrequentAction     object
FirstActionType         object
LastActionType          object
FirstPageVisited        object
LastPageVisited         object
customer_segments       object
dtype: object

In [51]:
data.select_dtypes(include= 'int64').dtypes

CustomerID                  int64
Age                         int64
NPS                         int64
ChurnLabel                  int64
PageViews                   int64
TimeSpent(minutes)          int64
Logins                      int64
Rating                      int64
TotalPurchaseFrequency      int64
NumPaymentMethod            int64
num_calls                   int64
num_emails                  int64
num_chats                   int64
InteractionDuration_days    int64
Action_count                int64
TotalDaysActive             int64
ActivityDuration_days       int64
TotalPageVisits             int64
unique_pages                int64
Recency_days                int64
InactivityFlag              int64
ActiveInLastWeek            int64
TotalEmailsSent             int64
TotalEmailsOpened           int64
TotalEmailsClicked          int64
EverOpened                  int64
EverClicked                 int64
RecencyLastOpen_days        int64
RecencyLastClick_days       int64
dtype: object

In [52]:
data.select_dtypes(include= 'float64').dtypes

TotalPurchaseValue            float64
AvgLatePayment                float64
AvgTimeBetweenActions_secs    float64
ActionsPerDay                 float64
ActionsLast30Days             float64
AVGOpenDays                   float64
AVGClickDays                  float64
AvgOpenDelay_days             float64
AvgClickDelay_days            float64
OpenRate                      float64
ClickRate                     float64
ClickToOpenRate               float64
dtype: object

### Encoding variables

In [53]:
'''
data.select_dtypes(include=['object']).dtypes
data.select_dtypes(include= 'datetime').dtypes
data.select_dtypes(include= 'int64').dtypes
data.select_dtypes(include= 'category').dtypes
'''

"\ndata.select_dtypes(include=['object']).dtypes\ndata.select_dtypes(include= 'datetime').dtypes\ndata.select_dtypes(include= 'int64').dtypes\ndata.select_dtypes(include= 'category').dtypes\n"

In [54]:
nominal_cols= ['Gender', 'Frequency', 
               'FirstActionType', 'TotalInteractionType', 'PaymentTypes',
               'FirstInteractionType', 'LastInteractionType'] # ohe

high_cardinal_cols = ['Location',  'ProductList', 'MostCommonAction', 
                'LastPageVisited', 'FirstPageVisited', 'LastActionType', 'LeastFrequentAction'] #mean encoding


ordinal_cols = ['Segment', 'Plan','customer_segments'] #label encoding 

# target encode the ChurnLabel : 'binary'

In [55]:
data[['Segment']].value_counts()

Segment
Segment C    4199
Segment A    4157
Segment B    4127
Name: count, dtype: int64

#### one hot encoding: nominal columns

In [56]:
# encode nominal cols
oh_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
oh_encoded = oh_encoder.fit_transform(data[nominal_cols])

ohe_df = pd.DataFrame(oh_encoded, columns=oh_encoder.get_feature_names_out(nominal_cols))

ohe_df

,Gender_Female,Gender_Male,Frequency_Daily,Frequency_Monthly,Frequency_Weekly,FirstActionType_Add to Cart,FirstActionType_Click,FirstActionType_Search,TotalInteractionType_Call,"TotalInteractionType_Call,Chat",...,TotalInteractionType_Chat,"TotalInteractionType_Chat,Email",TotalInteractionType_Email,"PaymentTypes_Bank Transfer,Credit Card,PayPal",FirstInteractionType_Call,FirstInteractionType_Chat,FirstInteractionType_Email,LastInteractionType_Call,LastInteractionType_Chat,LastInteractionType_Email
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
3,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12478,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
12479,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
12480,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
12481,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
12482,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0

#### TargetEncoding categorical, high cardinal columns

In [57]:
# Target encode high cardinality columns
target_encoder = TargetEncoder(categories='auto', target_type='continuous', smooth='auto', random_state=42)

target_encoder.fit(data[high_cardinal_cols], data['TotalPurchaseValue'])
target_encoded = target_encoder.transform(data[high_cardinal_cols])

target_df = pd.DataFrame(target_encoded, columns=target_encoder.get_feature_names_out(input_features=high_cardinal_cols))

target_df

,Location,ProductList,MostCommonAction,LastPageVisited,FirstPageVisited,LastActionType,LeastFrequentAction
0,3108.706989,3994.720000,2788.687471,2742.935481,2799.652196,2792.118233,2765.943294
1,1564.549407,2844.350000,2771.215786,2776.719365,2633.735455,2764.365907,2767.863174
2,1866.520000,1866.520000,2788.687471,2692.721793,2721.790018,2792.118233,2790.584749
3,2530.178283,1378.640000,2825.513863,2692.721793,2749.509019,2792.118233,2790.584749
4,3719.272176,2425.050000,2748.317094,2720.934285,2686.597116,2792.118233,2767.863174
...,...,...,...,...,...,...,...
12478,1196.560000,1196.560000,2748.317094,2717.369816,2806.162724,2764.365907,2951.121507
12479,710.570000,531.088868,2721.417899,2841.795028,2840.139064,2753.807584,2721.417899
12480,5154.420000,5154.420000,2788.687471,2742.935481,2793.643999,2764.365907,2765.943294
12481,3326.980918,6055.160000,2771.215786,2828.047621,2840.139064,2764.365907,2790.584749
12482,1815.666664,578.959595,2748.317094,2823.212801,2806.162724,2753.807584,2765.943294

#### label encoding ordinal columns

In [58]:
# Initialize and fit LabelEncoder
le = LabelEncoder()

le_df=pd.DataFrame(columns= ordinal_cols)

for c in ordinal_cols:
    le_df[c] = le.fit_transform(data[c])

le_df

       Segment  Plan  customer_segments
0            1     6                  0
1            2    12                  3
2            1     5                  2
3            2    15                  1
4            2     0                  1
...        ...   ...                ...
12478        0     5                  1
12479        0     8                  3
12480        2     2                  2
12481        0     9                  2
12482        2    11                  1

[12483 rows x 3 columns]

### drop redundant columns

In [ ]:
#drop irrelevant columns and original nominal columns that were one hot encoded: ohe_df created new differnet col names
data.drop(columns=['CustomerID', 'Name', 'Age', 'Email', 'Phone', 'Address', 
                   'Gender', 'Frequency', 
               'FirstActionType', 'TotalInteractionType', 'FirstInteractionType', 'LastInteractionType',
                 'PaymentTypes', 'Comment', 'PaymentTypes',
               'Location',  'ProductList', 'MostCommonAction', 
                'LastPageVisited', 'FirstPageVisited', 'LastActionType', 
                'LeastFrequentAction','Segment', 'Plan','customer_segments'
                ], axis=1, inplace = True)

In [60]:
data.columns

Index(['NPS', 'ChurnLabel', 'Timestamp', 'Start_Date', 'End_Date', 'PageViews',
       'TimeSpent(minutes)', 'Logins', 'Rating', 'TotalPurchaseFrequency',
       'TotalPurchaseValue', 'AvgLatePayment', 'num_calls', 'num_emails',
       'num_chats', 'FirstInteractionDate', 'LastInteractionDate',
       'InteractionDuration_days', 'Action_count', 'FirstActionTime',
       'LastActionTime', 'AvgTimeBetweenActions_secs', 'TotalDaysActive',
       'ActivityDuration_days', 'ActionsPerDay', 'most_recent_action_date',
       'TotalPageVisits', 'unique_pages', 'Recency_days', 'InactivityFlag',
       'ActionsLast30Days', 'ActiveInLastWeek', 'TotalEmailsSent',
       'TotalEmailsOpened', 'TotalEmailsClicked', 'LastEmailSentDate',
       'LastEmailOpenedDate', 'LastEmailClickedDate', 'AVGOpenDays',
       'AVGClickDays', 'AvgOpenDelay_days', 'AvgClickDelay_days', 'OpenRate',
       'ClickRate', 'ClickToOpenRate', 'EverOpened', 'EverClicked',
       'RecencyLastOpen_days', 'RecencyLastClick_days'],
      dtype='object')

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12483 entries, 0 to 12482
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   NPS                         12483 non-null  int64
 1   ChurnLabel                  12483 non-null  int64
 2   Timestamp                   12483 non-null  datetime64[ns]
 3   Start_Date                  12483 non-null  datetime64[ns]
 4   End_Date                    12483 non-null  datetime64[ns]
 5   PageViews                   12483 non-null  int64
 6   TimeSpent(minutes)          12483 non-null  int64
 7   Logins                      12483 non-null  int64
 8   Rating                      12483 non-null  int64
 9   TotalPurchaseFrequency      12483 non-null  int64
 10  TotalPurchaseValue          12483 non-null  float64
 11  AvgLatePayment              12483 non-null  float64
 12  num_calls                   12483 non-null  int64
 13  num_emails                  12483 non-null  int64
 14  num_chats                   12483 non-null  int64
 15  FirstInteractionDate        12483 non-null  datetime64[ns]
 16  LastInteractionDate         12483 non-null  datetime64[ns]
 17  InteractionDuration_days    12483 non-null  int64
 18  Action_count                12483 non-null  int64
 19  FirstActionTime             12483 non-null  datetime64[ns]
 20  LastActionTime              12483 non-null  datetime64[ns]
 21  AvgTimeBetweenActions_secs  12483 non-null  float64
 22  TotalDaysActive             12483 non-null  int64
 23  ActivityDuration_days       12483 non-null  int64
 24  ActionsPerDay               12483 non-null  float64
 25  most_recent_action_date     12483 non-null  datetime64[ns]
 26  TotalPageVisits             12483 non-null  int64
 27  unique_pages                12483 non-null  int64
 28  Recency_days                12483 non-null  int64
 29  InactivityFlag              12483 non-null  int64
 30  ActionsLast30Days           12483 non-null  float64
 31  ActiveInLastWeek            12483 non-null  int64
 32  TotalEmailsSent             12483 non-null  int64
 33  TotalEmailsOpened           12483 non-null  int64
 34  TotalEmailsClicked          12483 non-null  int64
 35  LastEmailSentDate           12483 non-null  datetime64[ns]
 36  LastEmailOpenedDate         12483 non-null  datetime64[ns]
 37  LastEmailClickedDate        12483 non-null  datetime64[ns]
 38  AVGOpenDays                 12483 non-null  float64
 39  AVGClickDays                12483 non-null  float64
 40  AvgOpenDelay_days           12483 non-null  float64
 41  AvgClickDelay_days          12483 non-null  float64
 42  OpenRate                    12483 non-null  float64
 43  ClickRate                   12483 non-null  float64
 44  ClickToOpenRate             12483 non-null  float64
 45  EverOpened                  12483 non-null  int64
 46  EverClicked                 12483 non-null  int64
 47  RecencyLastOpen_days        12483 non-null  int64
 48  RecencyLastClick_days       12483 non-null  int64
dtypes: datetime64[ns](11), float64(12), int64(26)
memory usage: 4.7 MB

### concatenate original data and all encoded columns

In [62]:
encoded_data = pd.concat([ohe_df, data, target_df, le_df], axis=1)

In [63]:
encoded_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12483 entries, 0 to 12482
Data columns (total 81 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Gender_Female                                  12483 non-null  float64
 1   Gender_Male                                    12483 non-null  float64
 2   Frequency_Daily                                12483 non-null  float64
 3   Frequency_Monthly                              12483 non-null  float64
 4   Frequency_Weekly                               12483 non-null  float64
 5   FirstActionType_Add to Cart                    12483 non-null  float64
 6   FirstActionType_Click                          12483 non-null  float64
 7   FirstActionType_Search                         12483 non-null  float64
 8   TotalInteractionType_Call                      12483 non-null  float64
 9   TotalInteractionType_Call,Chat                 12483 non-null  float64
 10  TotalInteractionType_Call,Chat,Email           12483 non-null  float64
 11  TotalInteractionType_Call,Email                12483 non-null  float64
 12  TotalInteractionType_Chat                      12483 non-null  float64
 13  TotalInteractionType_Chat,Email                12483 non-null  float64
 14  TotalInteractionType_Email                     12483 non-null  float64
 15  PaymentTypes_Bank Transfer,Credit Card,PayPal  12483 non-null  float64
 16  FirstInteractionType_Call                      12483 non-null  float64
 17  FirstInteractionType_Chat                      12483 non-null  float64
 18  FirstInteractionType_Email                     12483 non-null  float64
 19  LastInteractionType_Call                       12483 non-null  float64
 20  LastInteractionType_Chat                       12483 non-null  float64
 21  LastInteractionType_Email                      12483 non-null  float64
 22  NPS                                            12483 non-null  int64
 23  ChurnLabel                                     12483 non-null  int64
 24  Timestamp                                      12483 non-null  datetime64[ns]
 25  Start_Date                                     12483 non-null  datetime64[ns]
 26  End_Date                                       12483 non-null  datetime64[ns]
 27  PageViews                                      12483 non-null  int64
 28  TimeSpent(minutes)                             12483 non-null  int64
 29  Logins                                         12483 non-null  int64
 30  Rating                                         12483 non-null  int64
 31  TotalPurchaseFrequency                         12483 non-null  int64
 32  TotalPurchaseValue                             12483 non-null  float64
 33  AvgLatePayment                                 12483 non-null  float64
 34  num_calls                                      12483 non-null  int64
 35  num_emails                                     12483 non-null  int64
 36  num_chats                                      12483 non-null  int64
 37  FirstInteractionDate                           12483 non-null  datetime64[ns]
 38  LastInteractionDate                            12483 non-null  datetime64[ns]
 39  InteractionDuration_days                       12483 non-null  int64
 40  Action_count                                   12483 non-null  int64
 41  FirstActionTime                                12483 non-null  datetime64[ns]
 42  LastActionTime                                 12483 non-null  datetime64[ns]
 43  AvgTimeBetweenActions_secs                     12483 non-null  float64
 44  TotalDaysActive                                12483 non-null  int64
 45  ActivityDuration_days                          12483 non-null  int64
 46  ActionsPerDay                                  12483 non-null  float64
 47  most_recent_action_date                        12483 non-null  datetime64[ns]
 48  TotalPageVisits                                12483 non-null  int64
 49  unique_pages                                   12483 non-null  int64
 50  Recency_days                                   12483 non-null  int64
 51  InactivityFlag                                 12483 non-null  int64
 52  ActionsLast30Days                              12483 non-null  float64
 53  ActiveInLastWeek                               12483 non-null  int64
 54  TotalEmailsSent                                12483 non-null  int64
 55  TotalEmailsOpened                              12483 non-null  int64
 56  TotalEmailsClicked                             12483 non-null  int64
 57  LastEmailSentDate                              12483 non-null  datetime64[ns]
 58  LastEmailOpenedDate                            12483 non-null  datetime64[ns]
 59  LastEmailClickedDate                           12483 non-null  datetime64[ns]
 60  AVGOpenDays                                    12483 non-null  float64
 61  AVGClickDays                                   12483 non-null  float64
 62  AvgOpenDelay_days                              12483 non-null  float64
 63  AvgClickDelay_days                             12483 non-null  float64
 64  OpenRate                                       12483 non-null  float64
 65  ClickRate                                      12483 non-null  float64
 66  ClickToOpenRate                                12483 non-null  float64
 67  EverOpened                                     12483 non-null  int64
 68  EverClicked                                    12483 non-null  int64
 69  RecencyLastOpen_days                           12483 non-null  int64
 70  RecencyLastClick_days                          12483 non-null  int64
 71  Location                                       12483 non-null  float64
 72  ProductList                                    12483 non-null  float64
 73  MostCommonAction                               12483 non-null  float64
 74  LastPageVisited                                12483 non-null  float64
 75  FirstPageVisited                               12483 non-null  float64
 76  LastActionType                                 12483 non-null  float64
 77  LeastFrequentAction                            12483 non-null  float64
 78  Segment                                        12483 non-null  int64
 79  Plan                                           12483 non-null  int64
 80  customer_segments                              12483 non-null  int64
dtypes: datetime64[ns](11), float64(41), int64(29)
memory usage: 7.7 MB

### Engineer date columns

In [64]:
# Engineer Date columns

date_cols = encoded_data.select_dtypes(include = 'datetime64[ns]').columns.to_list()
date_cols

['Timestamp',
 'Start_Date',
 'End_Date',
 'FirstInteractionDate',
 'LastInteractionDate',
 'FirstActionTime',
 'LastActionTime',
 'most_recent_action_date',
 'LastEmailSentDate',
 'LastEmailOpenedDate',
 'LastEmailClickedDate']

In [65]:
for dc in date_cols:
    encoded_data[dc + '_Year'] = encoded_data[dc].dt.year
    encoded_data[dc + '_Month'] = encoded_data[dc].dt.month
    encoded_data[dc + '_Day'] = encoded_data[dc].dt.day

    encoded_data.drop(columns=[dc], axis=1, inplace=True)

In [28]:
encoded_data[['most_recent_action_date_Year','most_recent_action_date_Month','most_recent_action_date_Day', 
     'LastEmailSentDate_Year','LastEmailSentDate_Month', 'LastEmailSentDate_Day']].dtypes

most_recent_action_date_Year     int32
most_recent_action_date_Month    int32
most_recent_action_date_Day      int32
LastEmailSentDate_Year           int32
LastEmailSentDate_Month          int32
LastEmailSentDate_Day            int32
dtype: object

### save encoded data as a csv file

In [ ]:
encoded_data.to_csv('clean_data2.csv', index=False)