In [74]:
import pandas as pd 
import numpy as numpy
import matplotlib.pyplot as plt

In [75]:
pd.set_option('display.max_columns', None)

In [76]:
data = pd.read_excel(r"C:\Users\psxea2\Desktop\Amdaritelecomchurn\dataset.xlsx")
data

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,PurchaseHistory,SubscriptionDetails,ServiceInteractions,PaymentHistory,WebsiteUsage,ClickstreamData,EngagementMetrics,Feedback,MarketingCommunication,NPS,ChurnLabel,Timestamp
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,"[{'Product': 'Frozen Cocktail Mixes', 'Frequen...","{'Plan': 'Express', 'Start_Date': '2020-06-08'...","[{'Type': 'Call', 'Date': '2019-09-26'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 5}...","{'PageViews': 49, 'TimeSpent(minutes)': 15}","[{'Action': 'Add to Cart', 'Page': 'register',...","{'Logins': 19, 'Frequency': 'Weekly'}","{'Rating': 1, 'Comment': 'I move baby go small...","[{'Email_Sent': '2019-10-17', 'Email_Opened': ...",3,1,2020-01-27 01:36:49
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,"[{'Product': 'Watercraft Polishes', 'Frequency...","{'Plan': 'Pro', 'Start_Date': '2021-07-21', 'E...","[{'Type': 'Call', 'Date': '2020-01-05'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 3}...","{'PageViews': 100, 'TimeSpent(minutes)': 9}","[{'Action': 'Add to Cart', 'Page': 'homepage',...","{'Logins': 9, 'Frequency': 'Weekly'}","{'Rating': 2, 'Comment': 'Wish what bag cut li...","[{'Email_Sent': '2021-08-02', 'Email_Opened': ...",6,0,2019-01-06 18:30:03
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,"[{'Product': 'Vehicle Waxes, Polishes & Protec...","{'Plan': 'Essential', 'Start_Date': '2019-10-0...","[{'Type': 'Email', 'Date': '2019-10-09'}, {'Ty...","[{'Method': 'Credit Card', 'Late_Payments': 1}...","{'PageViews': 1, 'TimeSpent(minutes)': 97}","[{'Action': 'Search', 'Page': 'terms', 'Timest...","{'Logins': 19, 'Frequency': 'Monthly'}","{'Rating': 4, 'Comment': 'Some Democrat guess ...","[{'Email_Sent': '2021-08-29', 'Email_Opened': ...",3,0,2019-04-30 04:25:10
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,"[{'Product': 'Mouthwash', 'Frequency': 5, 'Val...","{'Plan': 'Smart', 'Start_Date': '2020-01-14', ...","[{'Type': 'Call', 'Date': '2020-08-28'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 36...","{'PageViews': 25, 'TimeSpent(minutes)': 31}","[{'Action': 'Click', 'Page': 'privacy', 'Times...","{'Logins': 4, 'Frequency': 'Daily'}","{'Rating': 1, 'Comment': 'Yard feel never miss...","[{'Email_Sent': '2021-02-03', 'Email_Opened': ...",1,1,2020-03-03 17:33:28
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,"[{'Product': 'Ice Cream Novelties', 'Frequency...","{'Plan': 'Basic', 'Start_Date': '2021-04-08', ...","[{'Type': 'Call', 'Date': '2019-04-10'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 0}...","{'PageViews': 77, 'TimeSpent(minutes)': 51}","[{'Action': 'Click', 'Page': 'privacy', 'Times...","{'Logins': 12, 'Frequency': 'Weekly'}","{'Rating': 3, 'Comment': 'Ten determine unit i...","[{'Email_Sent': '2022-03-11', 'Email_Opened': ...",3,0,2019-04-05 22:42:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12478,13479,Catherine Lee,55,Female,New Lauren,kgarcia@example.com,(977)150-1569x426,"836 Gonzalez Drive Apt. 334\nLake Kelly, RI 01667",Segment A,"[{'Product': 'Ice Cream Novelties', 'Frequency...","{'Plan': 'Essential', 'Start_Date': '2019-06-1...","[{'Type': 'Email', 'Date': '2021-02-17'}, {'Ty...","[{'Method': 'Credit Card', 'Late_Payments': 1}...","{'PageViews': 70, 'TimeSpent(minutes)': 57}","[{'Action': 'Add to Cart', 'Page': 'homepage',...","{'Logins': 22, 'Frequency': 'Daily'}","{'Rating': 2, 'Comment': 'Light appear fight l...","[{'Email_Sent': '2020-11-29', 'Email_Opened': ...",8,0,2022-01-27 00:27:28
12479,13480,Kimberly Johnson,29,Male,Randymouth,carrjennifer@example.org,485.014.7824x5235,3715 Wiggins Harbors Suite 139\nEast Gregorybo...,Segment A,"[{'Product': 'Straight Pins', 'Frequency': 1, ...","{'Plan': 'Flex', 'Start_Date': '2022-12-10', '...","[{'Type': 'Call', 'Date': '2022-11-05'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 1}...","{'PageViews': 71, 'TimeSpent(minutes)': 66}","[{'Action': 'Search', 'Page': 'category', 'Tim...","{'Logins': 25, 'Frequency': 'Weekly'}","{'Rating': 3, 'Comment': 'Yet very girl histor...","[{'Email_Sent': '2022-05-29', 'Email_Opened': ...",7,0,2020-06-14 23:04:47
12480,13481,Lisa Rodgers,38,Male,East Erin,william37@example.com,951-489-9554,"56050 Steven Summit Suite 383\nJohnmouth, NM 2...",Segment C,"[{'Product': 'Furisode Kimonos', 'Frequency': ...","{'Plan': 'Deluxe', 'Start_Date': '2021-07-04',...","[{'Type': 'Email', 'Date': '2020-05-22'}, {'Ty...","[{'Method': 'Credit Card', 'Late_Payments': 26...","{'PageViews': 96, 'TimeSpent(minutes)': 1}","[{'Action': 'Search', 'Page': 'author', 'Times...","{'Logins': 9, 'Frequency': 'Monthly'}","{'Rating': 5, 'Comment': 'Offer particularly s...","[{'Email_Sent': '2020-05-18', 'Email_Opened': ...",1,1,2020-10-13 15:09:13
12481,13482,Kristin Carey,26,Female,New Leah,josephcarter@example.net,001-335-464-3236x722,"72356 Teresa Rapid\nPorterborough, SC 40076",Segment A,"[{'Product': 'Sequins & Glitter', 'Frequency':...","{'Plan': 'Gold', 'Start_Date': '2020-07-21', '...","[{'Type': 'Call', 'Date': '2020-09-11'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 30...","{'PageViews': 63, 'TimeSpent(minutes)': 2}","[{'Action': 'Click', 'Page': 'post', 'Timestam...","{'Logins': 2, 'Frequency': 'Monthly'}","{'Rating': 5, 'Comment': 'Rest something conce...","[{'Email_Sent': '2021-09-05', 'Email_Opened': ...",0,0,2020-06-24 23:49:01
12482,13483,Melissa Carter,29,Male,West Amanda,regina88@example.net,816-238-9247,USCGC Lopez\nFPO AE 85542,Segment C,"[{'Product': 'Pool Brushes & Brooms', 'Frequen...","{'Plan': 'Prime', 'Start_Date': '2021-08-20', ...","[{'Type': 'Call', 'Date': '2019-02-17'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 11...","{'PageViews': 93, 'TimeSpent(minutes)': 6}","[{'Action': 'Add to Cart', 'Page': 'category',...","{'Logins': 6, 'Frequency': 'Weekly'}","{'Rating': 3, 'Comment': 'Indeed foot trouble ...","[{'Email_Sent': '2021-02-08', 'Email_Opened': ...",2,1,2022-07-14 07:27:52

#### initial data exploration

In [78]:
data.shape

(12483, 21)

In [79]:
data['PurchaseHistory'][0]

"[{'Product': 'Frozen Cocktail Mixes', 'Frequency': 8, 'Value': 884.43}, {'Product': 'Printer, Copier & Fax Machine Accessories', 'Frequency': 7, 'Value': 397.14}, {'Product': 'Hockey Stick Care', 'Frequency': 10, 'Value': 498.92}, {'Product': 'Guacamole', 'Frequency': 2, 'Value': 718.43}, {'Product': 'Mortisers', 'Frequency': 2, 'Value': 614.08}, {'Product': 'Rulers', 'Frequency': 6, 'Value': 221.68}, {'Product': 'Invitations', 'Frequency': 3, 'Value': 660.04}]"

In [86]:
import ast

In [87]:

normalised_df = pd.DataFrame({

    'CustomerID': data['CustomerID'],
    'purchaseHistory': data['PurchaseHistory']
})

normalised_df['purchaseHistory'] = normalised_df['purchaseHistory'].apply(ast.literal_eval)

In [88]:
normalised_df.dtypes

CustomerID          int64
purchaseHistory    object
dtype: object

In [89]:
normalised_df = pd.DataFrame(normalised_df)
normalised_df

       CustomerID                                    purchaseHistory
0            1001  [{'Product': 'Frozen Cocktail Mixes', 'Frequen...
1            1002  [{'Product': 'Watercraft Polishes', 'Frequency...
2            1003  [{'Product': 'Vehicle Waxes, Polishes & Protec...
3            1004  [{'Product': 'Mouthwash', 'Frequency': 5, 'Val...
4            1005  [{'Product': 'Ice Cream Novelties', 'Frequency...
...           ...                                                ...
12478       13479  [{'Product': 'Ice Cream Novelties', 'Frequency...
12479       13480  [{'Product': 'Straight Pins', 'Frequency': 1, ...
12480       13481  [{'Product': 'Furisode Kimonos', 'Frequency': ...
12481       13482  [{'Product': 'Sequins & Glitter', 'Frequency':...
12482       13483  [{'Product': 'Pool Brushes & Brooms', 'Frequen...

[12483 rows x 2 columns]

In [90]:
normalised_df['purchaseHistory'][0]

[{'Product': 'Frozen Cocktail Mixes', 'Frequency': 8, 'Value': 884.43},
 {'Product': 'Printer, Copier & Fax Machine Accessories',
  'Frequency': 7,
  'Value': 397.14},
 {'Product': 'Hockey Stick Care', 'Frequency': 10, 'Value': 498.92},
 {'Product': 'Guacamole', 'Frequency': 2, 'Value': 718.43},
 {'Product': 'Mortisers', 'Frequency': 2, 'Value': 614.08},
 {'Product': 'Rulers', 'Frequency': 6, 'Value': 221.68},
 {'Product': 'Invitations', 'Frequency': 3, 'Value': 660.04}]

In [91]:
normalised_df.explode('purchaseHistory')

       CustomerID                                    purchaseHistory
0            1001  {'Product': 'Frozen Cocktail Mixes', 'Frequenc...
0            1001  {'Product': 'Printer, Copier & Fax Machine Acc...
0            1001  {'Product': 'Hockey Stick Care', 'Frequency': ...
0            1001  {'Product': 'Guacamole', 'Frequency': 2, 'Valu...
0            1001  {'Product': 'Mortisers', 'Frequency': 2, 'Valu...
...           ...                                                ...
12481       13482  {'Product': 'Tractor Parts & Accessories', 'Fr...
12481       13482  {'Product': 'Video Cards & Adapters', 'Frequen...
12481       13482  {'Product': 'Clear Kerosene', 'Frequency': 3, ...
12481       13482  {'Product': 'Tripod Spreaders', 'Frequency': 8...
12482       13483  {'Product': 'Pool Brushes & Brooms', 'Frequenc...

[68628 rows x 2 columns]

In [92]:
normalised_df= normalised_df.explode('purchaseHistory')

In [93]:
normalised_df.columns

Index(['CustomerID', 'purchaseHistory'], dtype='object')

In [94]:
normalised_df

       CustomerID                                    purchaseHistory
0            1001  {'Product': 'Frozen Cocktail Mixes', 'Frequenc...
0            1001  {'Product': 'Printer, Copier & Fax Machine Acc...
0            1001  {'Product': 'Hockey Stick Care', 'Frequency': ...
0            1001  {'Product': 'Guacamole', 'Frequency': 2, 'Valu...
0            1001  {'Product': 'Mortisers', 'Frequency': 2, 'Valu...
...           ...                                                ...
12481       13482  {'Product': 'Tractor Parts & Accessories', 'Fr...
12481       13482  {'Product': 'Video Cards & Adapters', 'Frequen...
12481       13482  {'Product': 'Clear Kerosene', 'Frequency': 3, ...
12481       13482  {'Product': 'Tripod Spreaders', 'Frequency': 8...
12482       13483  {'Product': 'Pool Brushes & Brooms', 'Frequenc...

[68628 rows x 2 columns]

In [95]:
normalised_df['purchaseHistory'].apply(pd.Series)

                                         Product  Frequency   Value
0                          Frozen Cocktail Mixes          8  884.43
0      Printer, Copier & Fax Machine Accessories          7  397.14
0                              Hockey Stick Care         10  498.92
0                                      Guacamole          2  718.43
0                                      Mortisers          2  614.08
...                                          ...        ...     ...
12481                Tractor Parts & Accessories          9  845.64
12481                     Video Cards & Adapters          3  791.84
12481                             Clear Kerosene          3  908.41
12481                           Tripod Spreaders          8  238.25
12482                      Pool Brushes & Brooms          1  154.20

[68628 rows x 3 columns]

In [96]:

pd.concat([
    normalised_df.drop(columns=['purchaseHistory']),
    normalised_df['purchaseHistory'].apply(pd.Series)
], axis=1)

,CustomerID,Product,Frequency,Value
0,1001,Frozen Cocktail Mixes,8,884.43
0,1001,"Printer, Copier & Fax Machine Accessories",7,397.14
0,1001,Hockey Stick Care,10,498.92
0,1001,Guacamole,2,718.43
0,1001,Mortisers,2,614.08
...,...,...,...,...
12481,13482,Tractor Parts & Accessories,9,845.64
12481,13482,Video Cards & Adapters,3,791.84
12481,13482,Clear Kerosene,3,908.41
12481,13482,Tripod Spreaders,8,238.25
12482,13483,Pool Brushes & Brooms,1,154.20

### create a function to automatically normalise the  respective columns in the data

In [97]:
def normalize (df: pd.DataFrame,column:str, fk:str) -> pd.DataFrame:
    """
    - a function to extract respective columns and transform them as a DataFrame
    - respective columns will have a unique primary key and single value in each coulmn
    - the function outputs a dataframe with normalised columns

    """

    normalized_df = pd.DataFrame({
    fk: df[fk],
    column : df[column]
    })

    normalized_df[column]=normalized_df[column].apply(ast.literal_eval)


    if isinstance(normalized_df[column][0], list):
        normalized_df = normalized_df.explode(column)


    normalized_df = pd.concat([
    normalized_df.drop(columns = [column]),
    normalized_df[column].apply(pd.Series)
    ], axis=1)


    return normalized_df

In [98]:
data.columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'Location', 'Email', 'Phone',
       'Address', 'Segment', 'PurchaseHistory', 'SubscriptionDetails',
       'ServiceInteractions', 'PaymentHistory', 'WebsiteUsage',
       'ClickstreamData', 'EngagementMetrics', 'Feedback',
       'MarketingCommunication', 'NPS', 'ChurnLabel', 'Timestamp'],
      dtype='object')

##### test the function

In [99]:
normalize(data, 'PurchaseHistory', 'CustomerID')

,CustomerID,Product,Frequency,Value
0,1001,Frozen Cocktail Mixes,8,884.43
0,1001,"Printer, Copier & Fax Machine Accessories",7,397.14
0,1001,Hockey Stick Care,10,498.92
0,1001,Guacamole,2,718.43
0,1001,Mortisers,2,614.08
...,...,...,...,...
12481,13482,Tractor Parts & Accessories,9,845.64
12481,13482,Video Cards & Adapters,3,791.84
12481,13482,Clear Kerosene,3,908.41
12481,13482,Tripod Spreaders,8,238.25
12482,13483,Pool Brushes & Brooms,1,154.20

In [100]:
data['WebsiteUsage']

0        {'PageViews': 49, 'TimeSpent(minutes)': 15}
1        {'PageViews': 100, 'TimeSpent(minutes)': 9}
2         {'PageViews': 1, 'TimeSpent(minutes)': 97}
3        {'PageViews': 25, 'TimeSpent(minutes)': 31}
4        {'PageViews': 77, 'TimeSpent(minutes)': 51}
                            ...
12478    {'PageViews': 70, 'TimeSpent(minutes)': 57}
12479    {'PageViews': 71, 'TimeSpent(minutes)': 66}
12480     {'PageViews': 96, 'TimeSpent(minutes)': 1}
12481     {'PageViews': 63, 'TimeSpent(minutes)': 2}
12482     {'PageViews': 93, 'TimeSpent(minutes)': 6}
Name: WebsiteUsage, Length: 12483, dtype: object

In [ ]:
#check which columns need normalisation
data.columns.to_list()[9:18]

['PurchaseHistory',
 'SubscriptionDetails',
 'ServiceInteractions',
 'PaymentHistory',
 'WebsiteUsage',
 'ClickstreamData',
 'EngagementMetrics',
 'Feedback',
 'MarketingCommunication']

In [102]:
#use indices to slice the dataframe and get the column names in a list
data.iloc[:,9:18].columns.to_list()

['PurchaseHistory',
 'SubscriptionDetails',
 'ServiceInteractions',
 'PaymentHistory',
 'WebsiteUsage',
 'ClickstreamData',
 'EngagementMetrics',
 'Feedback',
 'MarketingCommunication']

In [103]:
#create a list of columns to normalize and apply the normalize function to each of those columns
cols_to_normalize = data.iloc[:,9:18].columns.to_list()

normalized_cols = {}

for col in cols_to_normalize:
    normalized_cols[col] = normalize(data, col, 'CustomerID')

In [104]:
# view the results of one of the  normalized columns: purchaseHistory
normalized_cols['PurchaseHistory']

,CustomerID,Product,Frequency,Value
0,1001,Frozen Cocktail Mixes,8,884.43
0,1001,"Printer, Copier & Fax Machine Accessories",7,397.14
0,1001,Hockey Stick Care,10,498.92
0,1001,Guacamole,2,718.43
0,1001,Mortisers,2,614.08
...,...,...,...,...
12481,13482,Tractor Parts & Accessories,9,845.64
12481,13482,Video Cards & Adapters,3,791.84
12481,13482,Clear Kerosene,3,908.41
12481,13482,Tripod Spreaders,8,238.25
12482,13483,Pool Brushes & Brooms,1,154.20

In [119]:
#view the columns in the data that do not need normalization (contain a single value per row)
single_val_cols= data.drop(columns=cols_to_normalize, axis=1)

In [120]:
single_val_cols.head()

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,NPS,ChurnLabel,Timestamp
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,3,1,2020-01-27 01:36:49
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,6,0,2019-01-06 18:30:03
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,3,0,2019-04-30 04:25:10
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,1,1,2020-03-03 17:33:28
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,3,0,2019-04-05 22:42:22

In [121]:
#data = pd.read_excel(r"C:\Users\psxea2\Desktop\Amdaritelecomchurn\dataset.xlsx")