#### Imports

In [1]:
import pandas as pd 
import numpy as np
import warnings
import matplotlib.pyplot as plt

In [2]:
warnings.filterwarnings("ignore")
pd.reset_option("all")
#pd.set_option('display.max_columns', None)
#pd.set_option("display.max_colwidth", None)

In [3]:
data = pd.read_excel(r"C:\Users\psxea2\Desktop\Amdaritelecomchurn\dataset.xlsx")

In [4]:
data.head()

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,PurchaseHistory,...,ServiceInteractions,PaymentHistory,WebsiteUsage,ClickstreamData,EngagementMetrics,Feedback,MarketingCommunication,NPS,ChurnLabel,Timestamp
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,"[{'Product': 'Frozen Cocktail Mixes', 'Frequen...",...,"[{'Type': 'Call', 'Date': '2019-09-26'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 5}...","{'PageViews': 49, 'TimeSpent(minutes)': 15}","[{'Action': 'Add to Cart', 'Page': 'register',...","{'Logins': 19, 'Frequency': 'Weekly'}","{'Rating': 1, 'Comment': 'I move baby go small...","[{'Email_Sent': '2019-10-17', 'Email_Opened': ...",3,1,2020-01-27 01:36:49
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,"[{'Product': 'Watercraft Polishes', 'Frequency...",...,"[{'Type': 'Call', 'Date': '2020-01-05'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 3}...","{'PageViews': 100, 'TimeSpent(minutes)': 9}","[{'Action': 'Add to Cart', 'Page': 'homepage',...","{'Logins': 9, 'Frequency': 'Weekly'}","{'Rating': 2, 'Comment': 'Wish what bag cut li...","[{'Email_Sent': '2021-08-02', 'Email_Opened': ...",6,0,2019-01-06 18:30:03
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,"[{'Product': 'Vehicle Waxes, Polishes & Protec...",...,"[{'Type': 'Email', 'Date': '2019-10-09'}, {'Ty...","[{'Method': 'Credit Card', 'Late_Payments': 1}...","{'PageViews': 1, 'TimeSpent(minutes)': 97}","[{'Action': 'Search', 'Page': 'terms', 'Timest...","{'Logins': 19, 'Frequency': 'Monthly'}","{'Rating': 4, 'Comment': 'Some Democrat guess ...","[{'Email_Sent': '2021-08-29', 'Email_Opened': ...",3,0,2019-04-30 04:25:10
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,"[{'Product': 'Mouthwash', 'Frequency': 5, 'Val...",...,"[{'Type': 'Call', 'Date': '2020-08-28'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 36...","{'PageViews': 25, 'TimeSpent(minutes)': 31}","[{'Action': 'Click', 'Page': 'privacy', 'Times...","{'Logins': 4, 'Frequency': 'Daily'}","{'Rating': 1, 'Comment': 'Yard feel never miss...","[{'Email_Sent': '2021-02-03', 'Email_Opened': ...",1,1,2020-03-03 17:33:28
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,"[{'Product': 'Ice Cream Novelties', 'Frequency...",...,"[{'Type': 'Call', 'Date': '2019-04-10'}, {'Typ...","[{'Method': 'Credit Card', 'Late_Payments': 0}...","{'PageViews': 77, 'TimeSpent(minutes)': 51}","[{'Action': 'Click', 'Page': 'privacy', 'Times...","{'Logins': 12, 'Frequency': 'Weekly'}","{'Rating': 3, 'Comment': 'Ten determine unit i...","[{'Email_Sent': '2022-03-11', 'Email_Opened': ...",3,0,2019-04-05 22:42:22

#### initial data exploration

In [5]:
data.shape

(12483, 21)

In [6]:
data['PurchaseHistory'][0]

"[{'Product': 'Frozen Cocktail Mixes', 'Frequency': 8, 'Value': 884.43}, {'Product': 'Printer, Copier & Fax Machine Accessories', 'Frequency': 7, 'Value': 397.14}, {'Product': 'Hockey Stick Care', 'Frequency': 10, 'Value': 498.92}, {'Product': 'Guacamole', 'Frequency': 2, 'Value': 718.43}, {'Product': 'Mortisers', 'Frequency': 2, 'Value': 614.08}, {'Product': 'Rulers', 'Frequency': 6, 'Value': 221.68}, {'Product': 'Invitations', 'Frequency': 3, 'Value': 660.04}]"

In [7]:
import ast

In [8]:

normalised_df = pd.DataFrame({

    'CustomerID': data['CustomerID'],
    'purchaseHistory': data['PurchaseHistory']
})

normalised_df['purchaseHistory'] = normalised_df['purchaseHistory'].apply(ast.literal_eval)

In [9]:
normalised_df.dtypes

CustomerID          int64
purchaseHistory    object
dtype: object

In [10]:
normalised_df = pd.DataFrame(normalised_df)
normalised_df

       CustomerID                                    purchaseHistory
0            1001  [{'Product': 'Frozen Cocktail Mixes', 'Frequen...
1            1002  [{'Product': 'Watercraft Polishes', 'Frequency...
2            1003  [{'Product': 'Vehicle Waxes, Polishes & Protec...
3            1004  [{'Product': 'Mouthwash', 'Frequency': 5, 'Val...
4            1005  [{'Product': 'Ice Cream Novelties', 'Frequency...
...           ...                                                ...
12478       13479  [{'Product': 'Ice Cream Novelties', 'Frequency...
12479       13480  [{'Product': 'Straight Pins', 'Frequency': 1, ...
12480       13481  [{'Product': 'Furisode Kimonos', 'Frequency': ...
12481       13482  [{'Product': 'Sequins & Glitter', 'Frequency':...
12482       13483  [{'Product': 'Pool Brushes & Brooms', 'Frequen...

[12483 rows x 2 columns]

In [11]:
normalised_df['purchaseHistory'][0]

[{'Product': 'Frozen Cocktail Mixes', 'Frequency': 8, 'Value': 884.43},
 {'Product': 'Printer, Copier & Fax Machine Accessories',
  'Frequency': 7,
  'Value': 397.14},
 {'Product': 'Hockey Stick Care', 'Frequency': 10, 'Value': 498.92},
 {'Product': 'Guacamole', 'Frequency': 2, 'Value': 718.43},
 {'Product': 'Mortisers', 'Frequency': 2, 'Value': 614.08},
 {'Product': 'Rulers', 'Frequency': 6, 'Value': 221.68},
 {'Product': 'Invitations', 'Frequency': 3, 'Value': 660.04}]

In [12]:
normalised_df.explode('purchaseHistory')

       CustomerID                                    purchaseHistory
0            1001  {'Product': 'Frozen Cocktail Mixes', 'Frequenc...
0            1001  {'Product': 'Printer, Copier & Fax Machine Acc...
0            1001  {'Product': 'Hockey Stick Care', 'Frequency': ...
0            1001  {'Product': 'Guacamole', 'Frequency': 2, 'Valu...
0            1001  {'Product': 'Mortisers', 'Frequency': 2, 'Valu...
...           ...                                                ...
12481       13482  {'Product': 'Tractor Parts & Accessories', 'Fr...
12481       13482  {'Product': 'Video Cards & Adapters', 'Frequen...
12481       13482  {'Product': 'Clear Kerosene', 'Frequency': 3, ...
12481       13482  {'Product': 'Tripod Spreaders', 'Frequency': 8...
12482       13483  {'Product': 'Pool Brushes & Brooms', 'Frequenc...

[68628 rows x 2 columns]

In [13]:
normalised_df= normalised_df.explode('purchaseHistory')

In [14]:
normalised_df.columns

Index(['CustomerID', 'purchaseHistory'], dtype='object')

In [15]:
normalised_df

       CustomerID                                    purchaseHistory
0            1001  {'Product': 'Frozen Cocktail Mixes', 'Frequenc...
0            1001  {'Product': 'Printer, Copier & Fax Machine Acc...
0            1001  {'Product': 'Hockey Stick Care', 'Frequency': ...
0            1001  {'Product': 'Guacamole', 'Frequency': 2, 'Valu...
0            1001  {'Product': 'Mortisers', 'Frequency': 2, 'Valu...
...           ...                                                ...
12481       13482  {'Product': 'Tractor Parts & Accessories', 'Fr...
12481       13482  {'Product': 'Video Cards & Adapters', 'Frequen...
12481       13482  {'Product': 'Clear Kerosene', 'Frequency': 3, ...
12481       13482  {'Product': 'Tripod Spreaders', 'Frequency': 8...
12482       13483  {'Product': 'Pool Brushes & Brooms', 'Frequenc...

[68628 rows x 2 columns]

In [16]:
normalised_df['purchaseHistory'].apply(pd.Series)

                                         Product  Frequency   Value
0                          Frozen Cocktail Mixes          8  884.43
0      Printer, Copier & Fax Machine Accessories          7  397.14
0                              Hockey Stick Care         10  498.92
0                                      Guacamole          2  718.43
0                                      Mortisers          2  614.08
...                                          ...        ...     ...
12481                Tractor Parts & Accessories          9  845.64
12481                     Video Cards & Adapters          3  791.84
12481                             Clear Kerosene          3  908.41
12481                           Tripod Spreaders          8  238.25
12482                      Pool Brushes & Brooms          1  154.20

[68628 rows x 3 columns]

In [17]:

pd.concat([
    normalised_df.drop(columns=['purchaseHistory']),
    normalised_df['purchaseHistory'].apply(pd.Series)
], axis=1)

,CustomerID,Product,Frequency,Value
0,1001,Frozen Cocktail Mixes,8,884.43
0,1001,"Printer, Copier & Fax Machine Accessories",7,397.14
0,1001,Hockey Stick Care,10,498.92
0,1001,Guacamole,2,718.43
0,1001,Mortisers,2,614.08
...,...,...,...,...
12481,13482,Tractor Parts & Accessories,9,845.64
12481,13482,Video Cards & Adapters,3,791.84
12481,13482,Clear Kerosene,3,908.41
12481,13482,Tripod Spreaders,8,238.25
12482,13483,Pool Brushes & Brooms,1,154.20

### create a function to automatically normalise the  respective columns in the data

In [18]:
def normalize (df: pd.DataFrame,column:str, fk:str) -> pd.DataFrame:
    """
    - a function to extract respective columns and transform them as a DataFrame
    - respective columns will have a unique primary key and single value in each coulmn
    - the function outputs a dataframe with normalised columns

    """

    normalized_df = pd.DataFrame({
    fk: df[fk],
    column : df[column]
    })

    normalized_df[column]=normalized_df[column].apply(ast.literal_eval)


    if isinstance(normalized_df[column][0], list):
        normalized_df = normalized_df.explode(column)


    normalized_df = pd.concat([
    normalized_df.drop(columns = [column]),
    normalized_df[column].apply(pd.Series)
    ], axis=1)


    return normalized_df

In [19]:
data.columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'Location', 'Email', 'Phone',
       'Address', 'Segment', 'PurchaseHistory', 'SubscriptionDetails',
       'ServiceInteractions', 'PaymentHistory', 'WebsiteUsage',
       'ClickstreamData', 'EngagementMetrics', 'Feedback',
       'MarketingCommunication', 'NPS', 'ChurnLabel', 'Timestamp'],
      dtype='object')

### test the normalisation function

In [20]:
normalize(data, 'PurchaseHistory', 'CustomerID')

,CustomerID,Product,Frequency,Value
0,1001,Frozen Cocktail Mixes,8,884.43
0,1001,"Printer, Copier & Fax Machine Accessories",7,397.14
0,1001,Hockey Stick Care,10,498.92
0,1001,Guacamole,2,718.43
0,1001,Mortisers,2,614.08
...,...,...,...,...
12481,13482,Tractor Parts & Accessories,9,845.64
12481,13482,Video Cards & Adapters,3,791.84
12481,13482,Clear Kerosene,3,908.41
12481,13482,Tripod Spreaders,8,238.25
12482,13483,Pool Brushes & Brooms,1,154.20

In [ ]:
#data['WebsiteUsage']

In [21]:
#check which columns need normalisation
data.columns.to_list()[9:18]

['PurchaseHistory',
 'SubscriptionDetails',
 'ServiceInteractions',
 'PaymentHistory',
 'WebsiteUsage',
 'ClickstreamData',
 'EngagementMetrics',
 'Feedback',
 'MarketingCommunication']

In [22]:
#use indices to slice the dataframe and get the column names in a list
data.iloc[:,9:18].columns.to_list()

['PurchaseHistory',
 'SubscriptionDetails',
 'ServiceInteractions',
 'PaymentHistory',
 'WebsiteUsage',
 'ClickstreamData',
 'EngagementMetrics',
 'Feedback',
 'MarketingCommunication']

In [23]:
#create a list of columns to normalize and apply the normalize function to each of those columns
cols_to_normalize = data.iloc[:,9:18].columns.to_list()

#create an empty dictionary to store the normalized dataframes:normalized_cols

normalized_cols = {} #The dictionary `normalized_cols` contains items where the keys are column names (strings), 
# and the values are pandas DataFrames. So, it is a dictionary of type `Dict[str, pd.DataFrame]`.


for col in cols_to_normalize:
    normalized_cols[col] = normalize(data, col, 'CustomerID')

In [24]:
# view the results of one of the  normalized columns: purchaseHistory
normalized_cols['PurchaseHistory']

,CustomerID,Product,Frequency,Value
0,1001,Frozen Cocktail Mixes,8,884.43
0,1001,"Printer, Copier & Fax Machine Accessories",7,397.14
0,1001,Hockey Stick Care,10,498.92
0,1001,Guacamole,2,718.43
0,1001,Mortisers,2,614.08
...,...,...,...,...
12481,13482,Tractor Parts & Accessories,9,845.64
12481,13482,Video Cards & Adapters,3,791.84
12481,13482,Clear Kerosene,3,908.41
12481,13482,Tripod Spreaders,8,238.25
12482,13483,Pool Brushes & Brooms,1,154.20

In [25]:
normalized_cols['WebsiteUsage']

       CustomerID  PageViews  TimeSpent(minutes)
0            1001         49                  15
1            1002        100                   9
2            1003          1                  97
3            1004         25                  31
4            1005         77                  51
...           ...        ...                 ...
12478       13479         70                  57
12479       13480         71                  66
12480       13481         96                   1
12481       13482         63                   2
12482       13483         93                   6

[12483 rows x 3 columns]

In [26]:
normalized_cols['ClickstreamData']

       CustomerID       Action      Page            Timestamp
0            1001  Add to Cart  register  2020-09-13 17:06:44
0            1001       Search     login  2022-03-30 14:51:52
0            1001        Click     about  2019-11-10 05:48:48
0            1001  Add to Cart     terms  2019-05-15 10:17:44
0            1001  Add to Cart    author  2022-07-14 03:40:53
...           ...          ...       ...                  ...
12482       13483       Search     terms  2020-05-25 09:12:57
12482       13483       Search       faq  2022-10-22 16:58:27
12482       13483       Search     index  2019-12-02 01:00:43
12482       13483  Add to Cart    author  2019-07-13 11:12:37
12482       13483  Add to Cart     index  2020-10-14 04:21:18

[319616 rows x 4 columns]

In [27]:
normalized_cols['EngagementMetrics']

       CustomerID  Logins Frequency
0            1001      19    Weekly
1            1002       9    Weekly
2            1003      19   Monthly
3            1004       4     Daily
4            1005      12    Weekly
...           ...     ...       ...
12478       13479      22     Daily
12479       13480      25    Weekly
12480       13481       9   Monthly
12481       13482       2   Monthly
12482       13483       6    Weekly

[12483 rows x 3 columns]

In [28]:
normalized_cols['Feedback']

       CustomerID  Rating                                            Comment
0            1001       1  I move baby go small big. Office institution s...
1            1002       2  Wish what bag cut life. Statement might opport...
2            1003       4  Some Democrat guess but short. Whether behind ...
3            1004       1  Yard feel never miss ask billion Congress. Fly...
4            1005       3  Ten determine unit interview challenge stock. ...
...           ...     ...                                                ...
12478       13479       2              Light appear fight lawyer where star.
12479       13480       3  Yet very girl history. Thing late dream you re...
12480       13481       5  Offer particularly single degree seem sound. S...
12481       13482       5  Rest something concern likely movie. Foot in i...
12482       13483       3  Indeed foot trouble heavy agreement cut. West ...

[12483 rows x 3 columns]

In [29]:
normalized_cols['MarketingCommunication']

       CustomerID  Email_Sent Email_Opened Email_Clicked
0            1001  2019-10-17   2022-01-12    2022-11-27
0            1001  2019-10-17   2022-01-12    2022-11-27
0            1001  2019-10-17   2022-01-12    2022-11-27
0            1001  2019-10-17   2022-01-12    2022-11-27
0            1001  2019-10-17   2022-01-12    2022-11-27
...           ...         ...          ...           ...
12482       13483  2021-02-08   2021-09-18    2022-04-11
12482       13483  2021-02-08   2021-09-18    2022-04-11
12482       13483  2021-02-08   2021-09-18    2022-04-11
12482       13483  2021-02-08   2021-09-18    2022-04-11
12482       13483  2021-02-08   2021-09-18    2022-04-11

[68762 rows x 4 columns]

In [30]:
normalized_cols['PaymentHistory']

       CustomerID         Method  Late_Payments
0            1001    Credit Card              5
0            1001         PayPal             11
0            1001  Bank Transfer             24
1            1002    Credit Card              3
1            1002         PayPal              3
...           ...            ...            ...
12481       13482         PayPal              3
12481       13482  Bank Transfer             34
12482       13483    Credit Card             11
12482       13483         PayPal              8
12482       13483  Bank Transfer             30

[37449 rows x 3 columns]

In [31]:
normalized_cols['ServiceInteractions']

       CustomerID   Type        Date
0            1001   Call  2019-09-26
0            1001   Chat  2021-07-25
0            1001  Email  2020-04-13
0            1001   Chat  2020-11-15
1            1002   Call  2020-01-05
...           ...    ...         ...
12482       13483   Call  2022-04-06
12482       13483   Call  2021-01-31
12482       13483   Chat  2021-11-12
12482       13483   Call  2022-06-10
12482       13483   Chat  2020-11-04

[254253 rows x 3 columns]

In [32]:
normalized_cols['SubscriptionDetails']

       CustomerID       Plan  Start_Date    End_Date
0            1001    Express  2020-06-08  2022-10-27
1            1002        Pro  2021-07-21  2022-05-07
2            1003  Essential  2019-10-05  2020-08-19
3            1004      Smart  2020-01-14  2022-03-27
4            1005      Basic  2021-04-08  2022-11-09
...           ...        ...         ...         ...
12478       13479  Essential  2019-06-15  2021-06-29
12479       13480       Flex  2022-12-10  2022-12-28
12480       13481     Deluxe  2021-07-04  2021-07-24
12481       13482       Gold  2020-07-21  2021-11-17
12482       13483      Prime  2021-08-20  2022-05-13

[12483 rows x 4 columns]

In [33]:
# Check if any of the normalized columns have multiple rows for the same CustomerID
# This will help identify columns that may need further normalization or investigation.

duplicate_id_status = {
# Dictionary comprehension to create a dictionary: multiple_rows_status- 
# where keys are column names and values are either True or False 
# indicating if there are multiple rows for the same CustomerID in that column's DataFrame.

    col: normalized_cols[col]['CustomerID'].duplicated(keep=False).any()
    for col in normalized_cols
} 

# List columns where the same CustomerID has multiple rows
cols_with_duplicate_idrows = [col for col, has_multiple in duplicate_id_status.items() if has_multiple]

print("Columns in normalized_cols where the same CustomerID appears in multiple rows:")
for col in cols_with_duplicate_idrows:
    print(f"- {col}")


print("\n")

print("Columns in normalized_cols where each row has a unique customerID:")
for col in normalized_cols:
    if not duplicate_id_status[col]:
        print(f"- {col}")  


duplicate_id_status

Columns in normalized_cols where the same CustomerID appears in multiple rows:
- PurchaseHistory
- ServiceInteractions
- PaymentHistory
- ClickstreamData
- MarketingCommunication


Columns in normalized_cols where each row has a unique customerID:
- SubscriptionDetails
- WebsiteUsage
- EngagementMetrics
- Feedback

{'PurchaseHistory': np.True_,
 'SubscriptionDetails': np.False_,
 'ServiceInteractions': np.True_,
 'PaymentHistory': np.True_,
 'WebsiteUsage': np.False_,
 'ClickstreamData': np.True_,
 'EngagementMetrics': np.False_,
 'Feedback': np.False_,
 'MarketingCommunication': np.True_}

In [34]:
"""Alternative approach to check for multiple rows per CustomerID
 This method compares the total number of rows to the number of unique CustomerIDs.
 If the total number of rows is greater than the number of unique CustomerIDs, 
 it indicates that there are multiple rows for some CustomerIDs in that particular dataframe.
"""

nonunique_idstatus = {
    col: len(normalized_cols[col]) > normalized_cols[col]['CustomerID'].nunique()
    for col in normalized_cols
}


# List the columns that have a dataframe  where the same CustomerID appears in multiple rows 
cols_with_nonunique_idrows = [col for col, has_multiple in nonunique_idstatus.items() if has_multiple]

print("Columns in normalized_cols where their dataframe has the same CustomerID appearing in multiple rows:")
for col in cols_with_nonunique_idrows:
    print(f"- {col}")

print("\n")  # Print a newline for better readability

cols_with_unique_idrows = [col for col in normalized_cols if not nonunique_idstatus[col]]
#print(cols_with_unique_idrows)

print("Columns in normalized_cols where each row in their dataframe has a unique customerID:")
for col in normalized_cols:
    if not nonunique_idstatus[col]:
        print(f"- {col}")  


nonunique_idstatus

Columns in normalized_cols where their dataframe has the same CustomerID appearing in multiple rows:
- PurchaseHistory
- ServiceInteractions
- PaymentHistory
- ClickstreamData
- MarketingCommunication


Columns in normalized_cols where each row in their dataframe has a unique customerID:
- SubscriptionDetails
- WebsiteUsage
- EngagementMetrics
- Feedback

{'PurchaseHistory': True,
 'SubscriptionDetails': False,
 'ServiceInteractions': True,
 'PaymentHistory': True,
 'WebsiteUsage': False,
 'ClickstreamData': True,
 'EngagementMetrics': False,
 'Feedback': False,
 'MarketingCommunication': True}

### further feature engineering on those normalized columns where their dataframes have the customerid appearing in multiple rows

In [35]:
cols_with_nonunique_idrows

['PurchaseHistory',
 'ServiceInteractions',
 'PaymentHistory',
 'ClickstreamData',
 'MarketingCommunication']

#### PurchaseHistory

In [36]:
normalized_cols['PurchaseHistory'].head()

   CustomerID                                    Product  Frequency   Value
0        1001                      Frozen Cocktail Mixes          8  884.43
0        1001  Printer, Copier & Fax Machine Accessories          7  397.14
0        1001                          Hockey Stick Care         10  498.92
0        1001                                  Guacamole          2  718.43
0        1001                                  Mortisers          2  614.08

In [37]:
import textwrap
# engineer features from the PurchaseHistory dataframe by aggregating data for each CustomerID
# Create a new column called total_purchases by applying 'sum' on the  Frequency column
# create a new column called total_value by applying 'sum' on the Value column
# create a new column called productslist by applying a lambda function that joins unique product names with commas
# group by CustomerID to ensure one row per customer

purchaseHistory = normalized_cols['PurchaseHistory'].groupby('CustomerID').agg(
    total_purchases=('Frequency', 'sum'),
    total_value= ('Value', 'sum'),
    productslist=('Product', 
                  lambda x: " ".join(
                    textwrap.wrap(', '.join(sorted(set(x))), 
                                width=40)
                  )    
)).reset_index()

purchaseHistory.head()

,CustomerID,total_purchases,total_value,productslist
0,1001,38,3994.72,"Frozen Cocktail Mixes, Guacamole, Hockey Stick..."
1,1002,4,2844.35,"Baby Protective Wear, Footbags, Watercraft Pol..."
2,1003,14,1866.52,"Fudge, Pipe Caps & Plugs, Vehicle Waxes, Polis..."
3,1004,28,1378.64,"Crêpe & Blini Pans, Electrical Switches, Mouth..."
4,1005,39,2425.05,"Audiobooks, Fire Extinguisher & Equipment Stor..."

In [38]:


def wrap_products(s: str, max_items: int = 4) -> str:
    """
    Args:
        s (str): A comma-separated string of product names.
        max_items (int): Maximum number of products to include per line. Default = 4.
    
    Returns:
        str: A multi-line string where each line contains up to `max_items` product names,
             separated by commas.
    """
    products = [p.strip() for p in s.split(",")]   # split the long list into product names
    chunks = [
        ",".join(products[i:i+max_items])         # group products into lines
        for i in range(0, len(products), max_items)
    ]

    return "\n".join(chunks)   # use <br> for HTML line breaks instead of \n


# Apply to your dataframe 
purchaseHistory["productslist"] = purchaseHistory["productslist"].apply(lambda x: wrap_products(x, max_items=3))


#purchaseHistory.head(10).style.format({"productslist": lambda v: v}, escape="html")


##from IPython.display import display

#style=purchaseHistory.head(5).style.set_properties(
    #subset=["productslist"], **{"white-space": "pre-wrap"}
#)

#display(style)

#### PaymentHistory

In [40]:
normalized_cols['PaymentHistory'].head()

   CustomerID         Method  Late_Payments
0        1001    Credit Card              5
0        1001         PayPal             11
0        1001  Bank Transfer             24
1        1002    Credit Card              3
1        1002         PayPal              3

In [41]:
normalized_cols['PaymentHistory']['Method'].value_counts()

Method
Credit Card      12483
PayPal           12483
Bank Transfer    12483
Name: count, dtype: int64

In [42]:
import textwrap
# engineer features from the PaymentHistory dataframe by aggregating data for each CustomerID
# Create a new column called NumPaymentMethod which is the count of unique values in Method column
# Create a new column called AvgLatePayment which is the mean of Late_Payments column


paymentHistory = normalized_cols['PaymentHistory'].groupby('CustomerID').agg(
    
    PaymentTypes=('Method', lambda x: ",".join(sorted(set(x)))),
    NumPaymentMethod=('Method', 'nunique'),
    #FreqBankPaymnt=('Method', lambda x: (x=='Bank').sum()),
    #FreqCreditCardPmt=('Method', lambda x: (x=='Card').sum()),
    #FreqPayPalPmt=('Method', lambda x: (x=='PayPal').sum()),
    AvgLatePayment=('Late_Payments', 'mean'),

).reset_index()

paymentHistory.head()

,CustomerID,PaymentTypes,NumPaymentMethod,AvgLatePayment
0,1001,"Bank Transfer,Credit Card,PayPal",3,13.333333
1,1002,"Bank Transfer,Credit Card,PayPal",3,3.333333
2,1003,"Bank Transfer,Credit Card,PayPal",3,2.666667
3,1004,"Bank Transfer,Credit Card,PayPal",3,26.333333
4,1005,"Bank Transfer,Credit Card,PayPal",3,0.666667

#### ServiceInteractions

In [43]:
normalized_cols['ServiceInteractions'].head()

   CustomerID   Type        Date
0        1001   Call  2019-09-26
0        1001   Chat  2021-07-25
0        1001  Email  2020-04-13
0        1001   Chat  2020-11-15
1        1002   Call  2020-01-05

In [44]:
normalized_cols['ServiceInteractions']['Type'].value_counts()

Type
Email    85359
Chat     84630
Call     84264
Name: count, dtype: int64

In [45]:
normalized_cols['ServiceInteractions']['Type'].isnull()

0        False
0        False
0        False
0        False
1        False
         ...
12482    False
12482    False
12482    False
12482    False
12482    False
Name: Type, Length: 254253, dtype: bool

In [46]:
#engineer features from the ServiceInteractions dataframe by aggregating data for each CustomerID
# Create a new column called ServiceInteractionType which is the count of unique values in Type column
#
normalized_cols['ServiceInteractions']['Date'] = pd.to_datetime(
    normalized_cols['ServiceInteractions']['Date'], errors='coerce'
)


ServiceInteractions = normalized_cols['ServiceInteractions'].groupby('CustomerID').agg(
    ServiceInteractionType=('Type', lambda x: ','.join(sorted(set(x)))),
    Num_SIT=('Type', 'nunique'),  
    MostFreq_SIT=('Type', lambda x: x.mode()[0] if not x.mode().empty else np.nan), 
    SIT_calls=('Type', lambda x: (x == 'Call').sum()),
    SIT_emails=('Type', lambda x: (x == 'Email').sum()),
    SIT_chats=('Type', lambda x: (x == 'Chat').sum()),
    FirstInteraction=('Date', 'min'),
    LastInteraction=('Date', 'max'),
    InteractionDuration_days=('Date', lambda x: (x.max() - x.min()).days + 1 if len(x) > 1 else 1)
)

ServiceInteractions.head()

,ServiceInteractionType,Num_SIT,MostFreq_SIT,SIT_calls,SIT_emails,SIT_chats,FirstInteraction,LastInteraction,InteractionDuration_days
CustomerID,,,,,,,,,
1001,"Call,Chat,Email",3,Chat,1,1,2,2019-09-26,2021-07-25,669
1002,"Call,Chat,Email",3,Email,5,10,4,2019-01-12,2022-12-13,1432
1003,"Call,Chat,Email",3,Call,1,1,1,2019-10-09,2022-01-04,819
1004,"Call,Chat,Email",3,Chat,17,18,24,2019-01-03,2022-11-10,1408
1005,"Call,Chat,Email",3,Email,4,5,1,2019-04-10,2022-12-19,1350

In [47]:
# For each customer, get the service type used on their first interaction
first_service_type = (
    normalized_cols['ServiceInteractions']
    .sort_values(['CustomerID', 'Date'])
    .groupby('CustomerID')
    .first()
    .reset_index()[['CustomerID', 'Type', 'Date']]
    .rename(columns={'Type': 'FirstServiceType', 'Date': 'FirstInteractionDate'})
)

first_service_type.head()

   CustomerID FirstServiceType FirstInteractionDate
0        1001             Call           2019-09-26
1        1002             Call           2019-01-12
2        1003            Email           2019-10-09
3        1004            Email           2019-01-03
4        1005             Call           2019-04-10

In [48]:
# For each customer, get the service type used on their last interaction
last_service_type = (
    normalized_cols['ServiceInteractions']
    .sort_values(['CustomerID', 'Date'])
    .groupby('CustomerID')
    .last()
    .reset_index()[['CustomerID', 'Type', 'Date']]
    .rename(columns={'Type': 'LastServiceType', 'Date': 'LastInteractionDate'})
)

last_service_type.head()

   CustomerID LastServiceType LastInteractionDate
0        1001            Chat          2021-07-25
1        1002           Email          2022-12-13
2        1003            Call          2022-01-04
3        1004           Email          2022-11-10
4        1005            Call          2022-12-19

In [49]:
# Add first and last service interaction type for each customer, avoiding duplicate columns and ordering as requested
serviceInteractions = normalized_cols['ServiceInteractions'].groupby('CustomerID').agg(
    ServiceInteractionType=('Type', lambda x: ','.join(sorted(set(x)))),
    Num_SIT=('Type', 'nunique'),   
    SIT_calls=('Type', lambda x: (x == 'Call').sum()),
    SIT_emails=('Type', lambda x: (x == 'Email').sum()),
    SIT_chats=('Type', lambda x: (x == 'Chat').sum())
).reset_index()

# Merge with first and last service type and date, then reorder columns
serviceInteractions = (
    serviceInteractions
    .merge(first_service_type, on='CustomerID', how='left')
    .merge(last_service_type, on='CustomerID', how='left')
    .rename(columns={
        'FirstServiceType': 'FirstInteractionType',
        'LastServiceType': 'LastInteractionType'
    })
)

# Reorder columns as specified
cols = [
    'CustomerID', 'ServiceInteractionType', 'Num_SIT', 'SIT_calls', 'SIT_emails', 'SIT_chats',
    'FirstInteractionDate', 'FirstInteractionType',
    'LastInteractionDate', 'LastInteractionType'
]
serviceInteractions = serviceInteractions[cols]

serviceInteractions.head()

,CustomerID,ServiceInteractionType,Num_SIT,SIT_calls,SIT_emails,SIT_chats,FirstInteractionDate,FirstInteractionType,LastInteractionDate,LastInteractionType
0,1001,"Call,Chat,Email",3,1,1,2,2019-09-26,Call,2021-07-25,Chat
1,1002,"Call,Chat,Email",3,5,10,4,2019-01-12,Call,2022-12-13,Email
2,1003,"Call,Chat,Email",3,1,1,1,2019-10-09,Email,2022-01-04,Call
3,1004,"Call,Chat,Email",3,17,18,24,2019-01-03,Email,2022-11-10,Email
4,1005,"Call,Chat,Email",3,4,5,1,2019-04-10,Call,2022-12-19,Call

In [50]:
cols_with_nonunique_idrows

['PurchaseHistory',
 'ServiceInteractions',
 'PaymentHistory',
 'ClickstreamData',
 'MarketingCommunication']

#### ClickstreamData

In [51]:
normalized_cols['ClickstreamData']['Action'].value_counts()

Action
Click          106697
Search         106483
Add to Cart    106436
Name: count, dtype: int64

In [52]:
normalized_cols['ClickstreamData']['Page'].value_counts()

Page
author      23002
about       22968
homepage    22938
main        22856
category    22839
post        22834
index       22829
register    22821
privacy     22814
login       22814
terms       22796
home        22795
faq         22715
search      22595
Name: count, dtype: int64

In [53]:
normalized_cols['ClickstreamData'].head()

   CustomerID       Action      Page            Timestamp
0        1001  Add to Cart  register  2020-09-13 17:06:44
0        1001       Search     login  2022-03-30 14:51:52
0        1001        Click     about  2019-11-10 05:48:48
0        1001  Add to Cart     terms  2019-05-15 10:17:44
0        1001  Add to Cart    author  2022-07-14 03:40:53

In [54]:
import textwrap

normalized_cols['ClickstreamData']['Timestamp'] = pd.to_datetime(
    normalized_cols['ClickstreamData']['Timestamp'], errors='coerce'
)

# End of dataset
ClickstreamData_end = normalized_cols['ClickstreamData']['Timestamp'].max()


ClickstreamData = normalized_cols['ClickstreamData'].groupby('CustomerID').agg(

    Action=('Action', lambda x: ','.join((sorted(set(x))))),
    Total_Actions=('Action', 'count'),
    uniqueActions=('Action', 'nunique'),   
    AddToCartFreq=('Action', lambda x: (x == 'Add to Cart').sum()),
    SearchFreq=('Action', lambda x: (x == 'Search').sum()),
    clickFreq=('Action', lambda x: (x == 'Click').sum()),
    FirstActionTime = ('Timestamp', 'min'),
    LastActionTime = ('Timestamp', 'max'),

    AvgTimeBetweenActions_secs=('Timestamp', lambda x: (
            np.mean(np.diff(np.sort(x.values)).astype('timedelta64[s]').astype(int))
            if len(x) > 1 else 0)),

    TotalDaysActive = ('Timestamp', lambda x: x.dt.date.nunique()),
    MostCommonAction= ('Action', lambda x: ", ".join(x.value_counts().index[x.value_counts() == x.value_counts().max()])
                    ),
    LeastFrequentAction= ('Action', 
                lambda x: ", ".join(x.value_counts().index[x.value_counts() == x.value_counts().min()])
                ),
    ActivityDuration_days = ('Timestamp', lambda x: (x.max() - x.min()).days + 1 if len(x) > 1 else 1),
    ActionsPerDay=('Timestamp', lambda x: len(x) / x.dt.date.nunique()),
    TotalPageVisits=('Page', 'count'),


    uniquePgs=('Page', 'nunique'),
    #PageTitles=('Page', lambda x: ",".join(sorted(set(x)))),
    PageTitles=(
            "Page",
            lambda x: " ".join(
                textwrap.wrap(",".join(sorted(set(x))), width=30))
        ),
    MostVisitedPg=('Page', lambda x: x.value_counts().idxmax() if not x.empty else np.nan),
    LeastVisitedPg=('Page', lambda x: x.value_counts().idxmin() if not x.empty else np.nan)
    
    ).reset_index()



ClickstreamData.head()

,CustomerID,Action,Total_Actions,uniqueActions,AddToCartFreq,SearchFreq,clickFreq,FirstActionTime,LastActionTime,AvgTimeBetweenActions_secs,TotalDaysActive,MostCommonAction,LeastFrequentAction,ActivityDuration_days,ActionsPerDay,TotalPageVisits,uniquePgs,PageTitles,MostVisitedPg,LeastVisitedPg
0,1001,"Add to Cart,Click,Search",24,3,8,12,4,2019-01-13 08:39:42,2022-11-07 02:24:31,5.235613e+06,23,Search,Click,1394,1.043478,24,13,"about,author,faq,home,homepage ,index,login,ma...",about,terms
1,1002,"Add to Cart,Click,Search",24,3,8,7,9,2019-04-17 04:22:41,2022-12-05 00:27:08,4.988046e+06,24,Click,Search,1328,1.000000,24,13,"about,category,faq,home,homepa ge,index,login,...",homepage,login
2,1003,"Add to Cart,Click,Search",12,3,2,7,3,2019-03-09 05:16:38,2022-11-02 15:59:43,1.048147e+07,12,Search,Add to Cart,1335,1.000000,12,7,"about,author,login,main,regist er,search,terms",terms,login
3,1004,"Add to Cart,Click,Search",47,3,15,16,16,2019-02-08 13:10:41,2022-12-08 18:10:18,2.628078e+06,46,"Click, Search",Add to Cart,1400,1.021739,47,14,"about,author,category,faq,home ,homepage,index...",category,terms
4,1005,"Add to Cart,Click,Search",30,3,17,4,9,2019-01-08 20:16:44,2022-12-30 23:37:00,4.326373e+06,30,Add to Cart,Search,1453,1.000000,30,12,"author,category,faq,homepage,i ndex,login,main...",main,privacy

In [56]:
ClickstreamData.columns

Index(['CustomerID', 'Action', 'Total_Actions', 'uniqueActions',
       'AddToCartFreq', 'SearchFreq', 'clickFreq', 'FirstActionTime',
       'LastActionTime', 'AvgTimeBetweenActions_secs', 'TotalDaysActive',
       'MostCommonAction', 'LeastFrequentAction', 'ActivityDuration_days',
       'ActionsPerDay', 'TotalPageVisits', 'uniquePgs', 'PageTitles',
       'MostVisitedPg', 'LeastVisitedPg'],
      dtype='object')

In [57]:
first_action_type = (
    normalized_cols['ClickstreamData']
    .sort_values(['CustomerID', 'Timestamp'])
    .groupby('CustomerID')
    .first()
    .reset_index()[['CustomerID', 'Action']]
    .rename(columns={'Action': 'FirstActionType'})
)

In [58]:
first_action_type.head()

   CustomerID FirstActionType
0        1001          Search
1        1002           Click
2        1003           Click
3        1004     Add to Cart
4        1005     Add to Cart

In [59]:
last_action_type = (
    normalized_cols['ClickstreamData']
    .sort_values(['CustomerID', 'Timestamp'])
    .groupby('CustomerID')
    .last()
    .reset_index()[['CustomerID', 'Action']]
    .rename(columns={'Action': 'LastActionType'})
)

In [60]:
last_action_type.head()

   CustomerID LastActionType
0        1001         Search
1        1002    Add to Cart
2        1003         Search
3        1004         Search
4        1005         Search

In [61]:
ClickstreamData.columns

Index(['CustomerID', 'Action', 'Total_Actions', 'uniqueActions',
       'AddToCartFreq', 'SearchFreq', 'clickFreq', 'FirstActionTime',
       'LastActionTime', 'AvgTimeBetweenActions_secs', 'TotalDaysActive',
       'MostCommonAction', 'LeastFrequentAction', 'ActivityDuration_days',
       'ActionsPerDay', 'TotalPageVisits', 'uniquePgs', 'PageTitles',
       'MostVisitedPg', 'LeastVisitedPg'],
      dtype='object')

In [62]:
# Merge with first and last action type and date, then reorder columns
ClickstreamData = (
    ClickstreamData
    .merge(first_action_type, on='CustomerID', how='left')
    .merge(last_action_type, on='CustomerID', how='left')
    
)

#Reorder columns as specified

cols = [
 'CustomerID',
 # Actions
 'Total_Actions', 'uniqueActions', 'AddToCartFreq', 'SearchFreq', 'clickFreq',
 'MostCommonAction', 'LeastFrequentAction', 'Action',
 # Time
 'FirstActionTime', 'LastActionTime', 'ActivityDuration_days', 
 'TotalDaysActive', 'ActionsPerDay',
 # Pages
 'TotalPageVisits', 'uniquePgs', 'MostVisitedPg', 'LeastVisitedPg', 'PageTitles'
]
ClickstreamData = ClickstreamData[cols]

ClickstreamData.head()

,CustomerID,Total_Actions,uniqueActions,AddToCartFreq,SearchFreq,clickFreq,MostCommonAction,LeastFrequentAction,Action,FirstActionTime,LastActionTime,ActivityDuration_days,TotalDaysActive,ActionsPerDay,TotalPageVisits,uniquePgs,MostVisitedPg,LeastVisitedPg,PageTitles
0,1001,24,3,8,12,4,Search,Click,"Add to Cart,Click,Search",2019-01-13 08:39:42,2022-11-07 02:24:31,1394,23,1.043478,24,13,about,terms,"about,author,faq,home,homepage ,index,login,ma..."
1,1002,24,3,8,7,9,Click,Search,"Add to Cart,Click,Search",2019-04-17 04:22:41,2022-12-05 00:27:08,1328,24,1.000000,24,13,homepage,login,"about,category,faq,home,homepa ge,index,login,..."
2,1003,12,3,2,7,3,Search,Add to Cart,"Add to Cart,Click,Search",2019-03-09 05:16:38,2022-11-02 15:59:43,1335,12,1.000000,12,7,terms,login,"about,author,login,main,regist er,search,terms"
3,1004,47,3,15,16,16,"Click, Search",Add to Cart,"Add to Cart,Click,Search",2019-02-08 13:10:41,2022-12-08 18:10:18,1400,46,1.021739,47,14,category,terms,"about,author,category,faq,home ,homepage,index..."
4,1005,30,3,17,4,9,Add to Cart,Search,"Add to Cart,Click,Search",2019-01-08 20:16:44,2022-12-30 23:37:00,1453,30,1.000000,30,12,main,privacy,"author,category,faq,homepage,i ndex,login,main..."

In [63]:

firstpagevisits = ( 
    normalized_cols['ClickstreamData']
    .sort_values(['CustomerID', 'Timestamp'])
    .groupby('CustomerID')
    .first()                                    
    .reset_index()[['CustomerID', 'Page']]
    .rename(columns={'Page': 'FirstPageVisited'})
)

lastpagevisits = ( 
    normalized_cols['ClickstreamData']
    .sort_values(['CustomerID', 'Timestamp'])
    .groupby('CustomerID')
    .last()                                      
    .reset_index()[['CustomerID', 'Page']]
    .rename(columns={'Page': 'LastPageVisited'})
)

In [64]:
ClickstreamData = (
    ClickstreamData
    .merge(firstpagevisits, on='CustomerID', how='left')
    .merge(lastpagevisits, on='CustomerID', how='left')
)

In [65]:
ClickstreamData.head()

,CustomerID,Total_Actions,uniqueActions,AddToCartFreq,SearchFreq,clickFreq,MostCommonAction,LeastFrequentAction,Action,FirstActionTime,...,ActivityDuration_days,TotalDaysActive,ActionsPerDay,TotalPageVisits,uniquePgs,MostVisitedPg,LeastVisitedPg,PageTitles,FirstPageVisited,LastPageVisited
0,1001,24,3,8,12,4,Search,Click,"Add to Cart,Click,Search",2019-01-13 08:39:42,...,1394,23,1.043478,24,13,about,terms,"about,author,faq,home,homepage ,index,login,ma...",main,author
1,1002,24,3,8,7,9,Click,Search,"Add to Cart,Click,Search",2019-04-17 04:22:41,...,1328,24,1.000000,24,13,homepage,login,"about,category,faq,home,homepa ge,index,login,...",homepage,faq
2,1003,12,3,2,7,3,Search,Add to Cart,"Add to Cart,Click,Search",2019-03-09 05:16:38,...,1335,12,1.000000,12,7,terms,login,"about,author,login,main,regist er,search,terms",author,about
3,1004,47,3,15,16,16,"Click, Search",Add to Cart,"Add to Cart,Click,Search",2019-02-08 13:10:41,...,1400,46,1.021739,47,14,category,terms,"about,author,category,faq,home ,homepage,index...",category,about
4,1005,30,3,17,4,9,Add to Cart,Search,"Add to Cart,Click,Search",2019-01-08 20:16:44,...,1453,30,1.000000,30,12,main,privacy,"author,category,faq,homepage,i ndex,login,main...",register,post

In [66]:
    # --- Add recency features ---: how long ago the customer interacted with the website
ClickstreamData['Recency_days'] = (ClickstreamData_end - ClickstreamData['LastActionTime']).dt.days

ClickstreamData['InactivityFlag'] = (ClickstreamData['Recency_days'] > 30).astype(int)



# Actions in last 30 days

# Define the cutoff date for "last 30 days"
# Example: if dataset_end = 2025-09-20, cutoff = 2025-08-21
last30_cutoff = ClickstreamData_end - pd.Timedelta(days=30)


# Count how many actions each customer performed in the last 30 days
actions_last30 = (
    normalized_cols['ClickstreamData']
    # 1. Filter rows where Timestamp >= cutoff (only keep last 30 days)
    .loc[normalized_cols['ClickstreamData']['Timestamp'] >= last30_cutoff]
    # 2. Group by CustomerID (each customer's activity)
    .groupby('CustomerID')
    # 3. Count number of rows (actions/events) per customer
    .size()
     # 4. Rename the result to "ActionsLast30Days"
    .rename('ActionsLast30Days')
    # 5. Reset index so it's a proper DataFrame with two columns:
    #    CustomerID | ActionsLast30Days
    .reset_index()
)
ClickstreamData = ClickstreamData.merge(actions_last30, on='CustomerID', how='left').fillna({'ActionsLast30Days': 0})

# Active in last week

# Define the cutoff date for "last 7 days"
# Example: if dataset_end = 2025-09-20, cutoff = 2025-09-13
last7_cutoff = ClickstreamData_end - pd.Timedelta(days=7)


# Get all customers who had at least one action in the last 7 days
# 1. Filter rows where Timestamp >= cutoff
# 2. Select only the CustomerID column
# 3. Take the unique IDs (so each customer appears once)
# Result = a NumPy array of active customer IDs
active_last7_customers = normalized_cols['ClickstreamData'].loc[
    normalized_cols['ClickstreamData']['Timestamp'] >= last7_cutoff, 'CustomerID'
].unique()


# Create a new binary flag column in ClickstreamData:
#  - 1 if this customer's ID is in the active_last7_customers list
#  - 0 otherwise
ClickstreamData['ActiveInLastWeek'] = ClickstreamData['CustomerID'].isin(active_last7_customers).astype(int)


ClickstreamData.head()

,CustomerID,Total_Actions,uniqueActions,AddToCartFreq,SearchFreq,clickFreq,MostCommonAction,LeastFrequentAction,Action,FirstActionTime,...,uniquePgs,MostVisitedPg,LeastVisitedPg,PageTitles,FirstPageVisited,LastPageVisited,Recency_days,InactivityFlag,ActionsLast30Days,ActiveInLastWeek
0,1001,24,3,8,12,4,Search,Click,"Add to Cart,Click,Search",2019-01-13 08:39:42,...,13,about,terms,"about,author,faq,home,homepage ,index,login,ma...",main,author,53,1,0.0,0
1,1002,24,3,8,7,9,Click,Search,"Add to Cart,Click,Search",2019-04-17 04:22:41,...,13,homepage,login,"about,category,faq,home,homepa ge,index,login,...",homepage,faq,25,0,1.0,0
2,1003,12,3,2,7,3,Search,Add to Cart,"Add to Cart,Click,Search",2019-03-09 05:16:38,...,7,terms,login,"about,author,login,main,regist er,search,terms",author,about,58,1,0.0,0
3,1004,47,3,15,16,16,"Click, Search",Add to Cart,"Add to Cart,Click,Search",2019-02-08 13:10:41,...,14,category,terms,"about,author,category,faq,home ,homepage,index...",category,about,22,0,1.0,0
4,1005,30,3,17,4,9,Add to Cart,Search,"Add to Cart,Click,Search",2019-01-08 20:16:44,...,12,main,privacy,"author,category,faq,homepage,i ndex,login,main...",register,post,0,0,3.0,1

#### MarketingCommunications

In [69]:
cols_with_nonunique_idrows

['PurchaseHistory',
 'ServiceInteractions',
 'PaymentHistory',
 'ClickstreamData',
 'MarketingCommunication']

In [70]:
normalized_cols['MarketingCommunication'].head()

   CustomerID  Email_Sent Email_Opened Email_Clicked
0        1001  2019-10-17   2022-01-12    2022-11-27
0        1001  2019-10-17   2022-01-12    2022-11-27
0        1001  2019-10-17   2022-01-12    2022-11-27
0        1001  2019-10-17   2022-01-12    2022-11-27
0        1001  2019-10-17   2022-01-12    2022-11-27

In [72]:
# Make sure columns are datetime
for col in ['Email_Sent', 'Email_Opened', 'Email_Clicked']:
    normalized_cols['MarketingCommunication'][col] = pd.to_datetime(
        normalized_cols['MarketingCommunication'][col],
        errors='coerce'
    )


MarketingComm_end = normalized_cols['MarketingCommunication']['Email_Sent'].max()

marketingComm = normalized_cols['MarketingCommunication'].groupby('CustomerID').agg(
    #Totals of each event
    TotalEmailsSent=('Email_Sent', 'count'),
    TotalEmailsOpened=('Email_Opened', lambda x: x.notna().sum()),
    TotalEmailsClicked=('Email_Clicked', lambda x: x.notna().sum()),
    LastEmailSentDate=('Email_Sent', 'max'),
    LastEmailOpenedDate=('Email_Opened', 'max'),
    LastEmailClickedDate=('Email_Clicked', 'max'),

    AvgOpenDelay_days=('Email_Opened', lambda x: 
                       np.mean((x - normalized_cols['MarketingCommunication'].loc[x.index, 'Email_Sent']).dt.days.dropna()) 
                       if x.notna().any() else np.nan),

    AvgClickDelay_days=('Email_Clicked', lambda x: 
                        np.mean((x - normalized_cols['MarketingCommunication'].loc[x.index, 'Email_Sent']).dt.days.dropna()) 
                        if x.notna().any() else np.nan)


).reset_index()
    

# Engagement ratios
marketingComm['OpenRate'] = marketingComm['TotalEmailsOpened'] / marketingComm['TotalEmailsSent']
marketingComm['ClickRate'] = marketingComm['TotalEmailsClicked'] / marketingComm['TotalEmailsSent']
marketingComm['ClickToOpenRate'] = marketingComm['TotalEmailsClicked'] / marketingComm['TotalEmailsOpened'].replace(0, np.nan)

# Engagement flags
marketingComm['EverOpened'] = (marketingComm['TotalEmailsOpened'] > 0).astype(int)
marketingComm['EverClicked'] = (marketingComm['TotalEmailsClicked'] > 0).astype(int)

# Recency
marketingComm['RecencyLastOpen_days'] = (MarketingComm_end - marketingComm['LastEmailOpenedDate']).dt.days
marketingComm['RecencyLastClick_days'] = (MarketingComm_end - marketingComm['LastEmailClickedDate']).dt.days

In [73]:
marketingComm.head()

,CustomerID,TotalEmailsSent,TotalEmailsOpened,TotalEmailsClicked,LastEmailSentDate,LastEmailOpenedDate,LastEmailClickedDate,AvgOpenDelay_days,AvgClickDelay_days,OpenRate,ClickRate,ClickToOpenRate,EverOpened,EverClicked,RecencyLastOpen_days,RecencyLastClick_days
0,1001,8,8,8,2019-10-17,2022-01-12,2022-11-27,818.0,1137.0,1.0,1.0,1.0,1,1,352,33
1,1002,9,9,9,2021-08-02,2021-11-20,2022-02-16,110.0,198.0,1.0,1.0,1.0,1,1,405,317
2,1003,8,8,8,2021-08-29,2022-07-28,2022-11-22,333.0,450.0,1.0,1.0,1.0,1,1,155,38
3,1004,10,10,10,2021-02-03,2021-07-12,2022-09-08,159.0,582.0,1.0,1.0,1.0,1,1,536,113
4,1005,7,7,7,2022-03-11,2022-09-20,2022-12-25,193.0,289.0,1.0,1.0,1.0,1,1,101,5

### Merge all normalized columns

In [ ]:
#data = pd.read_excel(r"C:\Users\psxea2\Desktop\Amdaritelecomchurn\dataset.xlsx")

In [78]:
# drop columns from the original data that have been normalized
data_reduced = data.drop(columns=cols_to_normalize, axis=1, inplace=False)

In [79]:
data_reduced.head()

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,NPS,ChurnLabel,Timestamp
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,3,1,2020-01-27 01:36:49
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,6,0,2019-01-06 18:30:03
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,3,0,2019-04-30 04:25:10
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,1,1,2020-03-03 17:33:28
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,3,0,2019-04-05 22:42:22

In [80]:
# Merge the reduced original data with the normalized columns that have unique CustomerID per row
for col in cols_with_unique_idrows:
    merged_data = data_reduced.merge(normalized_cols[col], on='CustomerID', how='left')

In [81]:
# Merge the data with the engineered features from the non-unique CustomerID dataframes

engineered_features = [purchaseHistory, paymentHistory, serviceInteractions, ClickstreamData, marketingComm]

for ef in engineered_features:
    merged_data = merged_data.merge(ef, on='CustomerID', how='left')

In [83]:
merged_data.head()

,CustomerID,Name,Age,Gender,Location,Email,Phone,Address,Segment,NPS,...,LastEmailClickedDate,AvgOpenDelay_days,AvgClickDelay_days,OpenRate,ClickRate,ClickToOpenRate,EverOpened,EverClicked,RecencyLastOpen_days,RecencyLastClick_days
0,1001,Mark Barrett,31,Male,Andrewfort,allison74@example.net,3192528777,"61234 Shelley Heights Suite 467\nCohentown, GU...",Segment B,3,...,2022-11-27,818.0,1137.0,1.0,1.0,1.0,1,1,352,33
1,1002,Jeremy Welch,66,Female,Millerhaven,fmiller@example.com,231-587-1818x8651,"4959 Jennifer Junction\nNew Angelaport, TN 87397",Segment C,6,...,2022-02-16,110.0,198.0,1.0,1.0,1.0,1,1,405,317
2,1003,Brandon Patel,36,Female,Lozanostad,jasonbrown@example.org,(270)633-9095,"38701 Amanda Brook Apt. 076\nKimshire, NJ 62516",Segment B,3,...,2022-11-22,333.0,450.0,1.0,1.0,1.0,1,1,155,38
3,1004,Tina Martin,62,Female,South Dustin,matthew62@example.net,050.081.8706x11982,"67324 Ashley Coves\nSouth John, RI 29650",Segment C,1,...,2022-09-08,159.0,582.0,1.0,1.0,1.0,1,1,536,113
4,1005,Christopher Rodriguez,68,Female,West James,shannonstrickland@example.org,+1-701-854-4915x724,"01169 Miller Mission\nWest Anthonyburgh, WY 47359",Segment C,3,...,2022-12-25,193.0,289.0,1.0,1.0,1.0,1,1,101,5

In [84]:
merged_data.columns

Index(['CustomerID', 'Name', 'Age', 'Gender', 'Location', 'Email', 'Phone',
       'Address', 'Segment', 'NPS', 'ChurnLabel', 'Timestamp', 'Rating',
       'Comment', 'total_purchases', 'total_value', 'productslist',
       'PaymentTypes', 'NumPaymentMethod', 'AvgLatePayment',
       'ServiceInteractionType', 'Num_SIT', 'SIT_calls', 'SIT_emails',
       'SIT_chats', 'FirstInteractionDate', 'FirstInteractionType',
       'LastInteractionDate', 'LastInteractionType', 'Total_Actions',
       'uniqueActions', 'AddToCartFreq', 'SearchFreq', 'clickFreq',
       'MostCommonAction', 'LeastFrequentAction', 'Action', 'FirstActionTime',
       'LastActionTime', 'ActivityDuration_days', 'TotalDaysActive',
       'ActionsPerDay', 'TotalPageVisits', 'uniquePgs', 'MostVisitedPg',
       'LeastVisitedPg', 'PageTitles', 'FirstPageVisited', 'LastPageVisited',
       'Recency_days', 'InactivityFlag', 'ActionsLast30Days',
       'ActiveInLastWeek', 'TotalEmailsSent', 'TotalEmailsOpened',
       'TotalEmailsClicked', 'LastEmailSentDate', 'LastEmailOpenedDate',
       'LastEmailClickedDate', 'AvgOpenDelay_days', 'AvgClickDelay_days',
       'OpenRate', 'ClickRate', 'ClickToOpenRate', 'EverOpened', 'EverClicked',
       'RecencyLastOpen_days', 'RecencyLastClick_days'],
      dtype='object')

In [82]:

merged_data.shape

(12483, 68)

In [85]:
merged_data['CustomerID'].nunique()

12483